const jpRegex = /(\W|^)(Canadian\ Football\ League|National\ Football\ League|Edgeworth\–Kuiper\ belt|Norwegian\ Forest\ cat|Prince\ Edward\ Island|grayscale\,\ greyscale|random\ access\ memory|German\ Shepherd\ Dog|artist\-in\-residence|association\ football|golden\ lion\ tamarin|Berwick\-upon\-Tweed|Golden\ Gate\ Bridge|Great\ Barrier\ Reef|license\ or\ licence|reverse\ engineering|American\ Shorthair|Labrador\ retriever|Northern\ Territory|assistant\ director|corporate\ identity|desktop\ publishing|role\-playing\ game|trading\ card\ game|American\ Wirehair|American\ football|British\ Shorthair|Canadian\ football|Chesterfield\ coat|Chimera\,\ chimera|Papua\ New\ Guinea|Yorkshire\ Terrier|cafe\ a\ la\ creme|domestic\ violence|personal\ computer|read\-only\ memory|real\ money\ trade|rhythm\ and\ blues|sexual\ harassment|three\ of\ a\ kind|British\ Columbia|Humboldt\ penguin|Japanese\ Bobtail|New\ South\ Wales|North\ Charleston|Russian\ roulette|South\ Charleston|Sturm\ und\ Drang|animation\ studio|audio\ commentary|cable\ television|college\ football|color\ television|crossword\ puzzle|department\ store|fashion\ designer|four\ of\ a\ kind|graphic\ designer|hard\ disk\ drive|money\ laundering|operating\ system|palmtop\ computer|press\ conference|public\ relations|pygmy\ chimpanzee|recording\ studio|transistor\ radio|Austria\-Hungary|Canadian\ dollar|Electra\ complex|North\ Kingstown|Port\-au\-Prince|Salt\ Lake\ City|South\ Kingstown|acoustic\ guitar|air\ conditioner|boarding\ school|cabin\ attendant|custard\ pudding|double\ negative|double\ negative|double\ standard|electric\ guitar|emperor\ penguin|fire\ salamander|fish\ and\ chips|football\ helmet|interior\ design|merry\ Christmas|merry\-go\-round|plate\ tectonics|science\ fiction|simulation\ game|stainless\ steel|stainless\ steel|super\,\ super\-|system\ operator|virtual\ reality|Charlottesville|Christmas\ tree|Great\ Pyrenees|Great\ Yarmouth|Jefferson\ City|North\ Carolina|Port\ of\ Spain|Siberian\ Husky|Silicon\ Valley|South\ Carolina|Table\ Mountain|Turkish\ Angora|United\ Nations|air\ compressor|arena\ football|business\ class|cash\ dispenser|chicken\ nugget|cocktail\ dress|cocktail\ party|cocktail\ sauce|computerization|figure\ skating|fortune\ cookie|gentoo\ penguin|golden\ hamster|graphic\ design|happy\ hardcore|home\ directory|instant\ camera|motion\ capture|neural\ network|parallel\ world|privacy\ policy|ranch\ dressing|remote\ control|salad\ dressing|scratch\ ticket|steering\ wheel|straight\ flush|telephone\ card|time\ traveller|toreador\ pants|troubleshooting|user\ interface|whale\ watching|word\ processor|American\ Curl|Atlantic\ City|Beverly\ Hills|Constantinople|Czechoslovakia|Delaware\ City|Great\ Britain|Guinea\-Bissau|Hamburg\ steak|Hamburg\ steak|Internet\ cafe|Little\ Cayman|New\ Brunswick|New\ Caledonia|New\ Hampshire|North\ Augusta|Oklahoma\ City|Saint\ Vincent|Scotland\ Yard|Scottish\ Fold|West\ Virginia|afternoon\ tea|arm\ wrestling|assault\ rifle|belt\ conveyor|cable\ network|cheese\ fondue|cherry\ tomato|computer\ game|electric\ bass|free\ software|fried\ chicken|graphics\ card|hunger\ strike|hyperinflation|jigsaw\ puzzle|kick\ baseball|mental\ health|monkey\ wrench|nanotechnology|parking\ meter|passion\ fruit|peanut\ butter|phenanthridine|plastic\ model|postproduction|public\ domain|question\ mark|radio\ control|record\ player|rehabilitation|revenge\ match|rock\ climbing|rocking\ chair|roller\ hockey|service\ games|stained\ glass|troubleshooter|upright\ piano|window\ washer|wire\ stripper|B\âton\-Rouge|Black\ Friday|Egyptian\ Mau|English\ horn|Fresnel\ lens|Grand\ Cayman|Great\ Plains|Jeffersontown|Massachusetts|Mickey\ Mouse|Minnie\ Mouse|North\ Dakota|Pearl\ Harbor|Port\ Augusta|Port\ Lincoln|Protestantism|Rhode\ Island|Russian\ Blue|South\ Dakota|St\.\ John\'s|Wonder\ Woman|World\ Series|aqua\ walking|barrier\-free|battle\ rifle|beach\ sandal|bottle\ green|bowling\ ball|boxing\ glove|brainstorming|collaboration|compact\ disc|contact\ lens|dental\ floss|dry\ cleaning|fiber\ optics|field\ hockey|figure\ skate|front\ office|globalization|good\ morning|happy\ ending|hit\ and\ run|hydroxylamine|impound\ yard|kick\ scooter|king\ penguin|lapis\ lazuli|lesser\ panda|lion\ tamarin|martial\ arts|masking\ tape|naphthyridine|oral\ history|pinch\ runner|postmodernism|pulp\ fiction|reality\ show|rollercoaster|scout\ report|scuba\ diving|scuba\ diving|second\ album|self\-service|shortcut\ key|sleeping\ bag|slot\ machine|social\ media|sound\ effect|sports\ drink|sudden\ death|teleportation|tennis\ court|time\ machine|toilet\ paper|tomato\ juice|vinyl\ record|Blue\ Hawaii|Carson\ City|Cayman\ Brac|Chesterfield|Cornish\ Rex|Donald\ Duck|George\ Town|Greco\-Roman|Indianapolis|Jersey\ City|Kuiper\ belt|Little\ Rock|Los\ Angeles|Mexico\ City|New\ Britain|New\ England|New\ Orleans|New\ Zealand|Newfoundland|Nova\ Scotia|Pennsylvania|Philadelphia|Quebec\ City|Saint\ Kitts|Santa\ Claus|Saskatchewan|Stanley\ Cup|Turkish\ Van|Welsh\ corgi|White\ House|\β\-carotene|acenaphthene|action\ game|arccotangent|baby\ boomer|beach\ towel|birdwatching|bisque\ doll|bottle\ cage|bungee\ jump|championship|cheerleading|cheeseburger|chewing\ gum|chiropractor|clock\ radio|coconut\ oil|coffee\ mill|comedy\ club|commissioner|countertenor|credit\ card|dark\ matter|data\ mining|disc\ jockey|eye\ contact|fan\ fiction|first\ class|flea\ market|floppy\ disk|focus\ group|full\ screen|giant\ panda|grand\ piano|handkerchief|hang\ glider|hate\ speech|illumination|jam\ session|light\ table|logic\ board|love\ letter|machine\ gun|maple\ syrup|marking\ pen|master\ plan|masturbation|music\ video|nail\ polish|night\ table|office\ pool|open\ source|phenanthrene|polyurethane|pop\ culture|prairie\ dog|presentation|ray\ tracing|road\ roller|rose\ quartz|royal\ flush|screen\ test|short\ pants|show\ window|slow\ motion|source\ code|stenographer|thoroughbred|three\-piece|thrill\ ride|time\ travel|touch\ panel|trench\ coat|troublemaker|web\ browser|white\ shirt|world\ music|Albuquerque|Bournemouth|Brazil\ nut|Chattanooga|Connecticut|Daisy\ Duck|Des\ Moines|Dutch\ wife|First\ Lady|Maine\ Coon|Minneapolis|Mississippi|New\ Guinea|New\ Jersey|New\ Mexico|Northampton|Port\ Louis|Saint\ John|Saint\ Paul|Saran\ Wrap|Scientology|Shakespeare|Sioux\ City|Southampton|Springfield|Super\ Bowl|Super\ Bowl|Tallahassee|Tesla\ coil|Texas\ City|Yellowknife|afterburner|air\ guitar|alexandrite|anti\-alias|application|autobicycle|autobicycle|bath\ towel|black\ bass|black\ hole|board\ game|bottle\ cap|calligraphy|candy\ cane|cannibalism|carbylamine|careerwoman|cat\'s\ eye|catastrophe|cauliflower|chain\ mail|cheerleader|chlorophyll|coffeemaker|combination|coming\ out|convertible|corn\ flake|corn\ syrup|curly\ hair|cybernetics|debit\ card|deep\ fryer|documentary|downpicking|dress\ code|dressmaking|epinephrine|flow\ chart|folk\ dance|frappuccino|full\ house|gerrymander|gingerbread|green\ peas|green\ tuff|guinea\ pig|hair\ dryer|hand\ model|home\ plate|homeostasis|horseradish|ice\ hockey|imagination|information|inspiration|interviewer|king\ cobra|kiwi\ fruit|knee\ socks|leg\ warmer|leisurewear|lemon\ balm|life\ cycle|light\ beer|light\ blue|live\ album|livermorium|maintenance|marker\ pen|marshmallow|microgramme|milligramme|motherboard|naphthalene|nationalism|nightingale|number\ one|ozone\ hole|partnership|patrol\ car|peace\ sign|perspective|phthalazine|planetarium|pole\ dance|polo\ shirt|pornography|psychometry|quarterback|quinazoline|quinoxaline|sandwichman|school\ bus|screwdriver|sewing\ set|sex\ appeal|slow\ loris|soft\ drink|sound\ card|speed\ bump|sponsorship|sports\ bar|sports\ bra|sweet\ corn|synthesizer|telestrator|totem\ pole|transgender|transmitter|transmitter|transmodern|transsexual|trump\ game|video\ card|video\ game|web\ design|white\ gold|white\ hole|ASCII\ art|Abyssinian|Bangladesh|Bridgeport|Caernarfon|California|Charleston|Chow\ Chow|Cincinnati|Coca\-Cola|Copenhagen|Devon\ Rex|Disneyland|Eurovision|Gloucester|Grenadines|Harrisburg|Iowa\ City|Lancashire|Manchester|Mary\ Jane|Montgomery|Montpelier|Montserrat|Nha\ Trang|Paralympic|Protestant|Providence|Queensland|Seychelles|Silk\ Road|Somaliland|Sri\ Lanka|Star\ Wars|Stonehenge|Washington|Wiktionary|adrenaline|amanuensis|anthracene|apostrophe|aquamarine|arctangent|asceticism|asparagine|baby\ boom|baby\ doll|ball\ game|base\ coat|basketball|bass\ drum|blackberry|bobblehead|breakdance|brightness|camerawork|camouflage|candy\ bar|card\ game|carotenoid|chandelier|cheesecake|chimpanzee|chinchilla|coelacanth|coin\ toss|collection|continuity|continuity|curriculum|d\éj\à\ vu|decoration|dedication|deep\ kiss|derivative|disc\ golf|dressmaker|euthanasia|fast\ food|folk\ song|foundation|free\ time|freelancer|full\ name|girlfriend|goalkeeper|golf\ club|guillotine|halterneck|hard\ disk|hartebeest|hat\ trick|helicopter|high\ card|high\ heel|high\-tech|home\ base|home\ page|homophobia|hot\ pants|hot\ sauce|hovercraft|hula\ hoop|ice\ candy|ice\ cream|isocyanide|isonitrile|laboratory|leadership|leafblower|lightsaber|lima\ bean|lip\ gloss|lip\ print|love\ song|main\ page|male\ rape|mangosteen|melancholy|microphone|millennium|minimalism|monitoring|monochrome|morpholine|nanosecond|narcissism|narcissist|news\ desk|newscaster|newsletter|nightstand|octadecane|olive\ oil|one\-piece|overblouse|part\-time|pentathlon|peppermint|photograph|ping\ pong|piperazine|piperidine|postmodern|proletaria|pyridazine|pyrimidine|recreation|recreation|referendum|repository|restaurant|rhinestone|salamander|scoreboard|screenshot|seat\ belt|simulation|sketchbook|skid\ mark|smartphone|snack\ bar|snow\ plow|snowmobile|soundtrack|speed\ gun|stewardess|stretching|stylesheet|subculture|supermodel|supplement|sweatshirt|tablespoon|tambourine|team\ play|tennessine|thank\ you|thermostat|tomography|trampoline|transistor|typewriter|typography|underscore|ununhexium|vegetarian|volleyball|wallflower|widescreen|wildebeest|world\ cup|Alexander|Ali\ Baba|Anchorage|Annapolis|AstroTurf|Australia|Babylonia|Badminton|Big\ Bang|Bluetooth|Byzantine|Cambridge|Champaign|Chartreux|Christian|Christmas|Cleveland|Dalmatian|Edinburgh|Frankfort|Gibraltar|Greenwich|Greenwich|Grey\ Cup|Halloween|Hampshire|Himalayan|Hollywood|Hotchkiss|Jefferson|Kingstown|Leicester|Liverpool|Louisiana|Luxemburg|Mauritius|Melbourne|Milwaukee|Minnesota|Nashville|New\ York|ObamaCare|Platonism|Reykjavik|Salisbury|San\ Jose|Shar\ Pei|Shih\ Tzu|Singapura|Swaziland|Tennessee|Tottenham|Vancouver|Wikipedia|Worcester|Yorkshire|ZIP\ code|accordion|acetylene|adventure|alabaster|algorithm|alligator|ampersand|anal\ sex|anarchism|anarchist|animation|animation|announcer|appliance|arccosine|artichoke|asparagus|assistant|associate|autopilot|azetidine|ball\ pen|beefsteak|berberine|beryllium|blackjack|blueberry|bookmaker|boomerang|boyfriend|brassiere|bulldozer|bush\ dog|butterfly|cameraman|cameraman|capsaicin|carbazole|carboline|celebrity|celluloid|chairlift|challenge|chameleon|champagne|check\-in|chocolate|chromakey|cigarette|cinnoline|cleansing|clipboard|coatdress|component|computing|condenser|consensus|coptisine|corkscrew|cotangent|cranberry|crinoline|crossover|crossword|dangerous|dashboard|deflation|deuterium|dictation|directory|dodgeball|ectoplasm|equalizer|escalator|euphonium|executive|eyeshadow|facsimile|fan\ club|felt\ pen|freelance|fruitcake|gabardine|galactose|georgette|glutamine|glyceride|glycoside|golf\ bag|gradation|guanidine|guitarist|gymnasium|gyroscope|hamburger|hardcover|harmonica|headlight|headphone|home\ run|home\ run|honeycomb|honeymoon|horoscope|hydrazine|hydrazone|hyperlink|hypertext|imidazole|inflation|installer|interline|interview|inventory|jitterbug|knowledge|knowledge|limousine|lizardman|low\ blow|mainboard|mannequin|manticore|margarine|marmalade|masochism|megaphone|mind\ map|miniskirt|modernism|moscovium|motocross|motorboat|newsflash|nice\ guy|nightclub|nostalgia|oganesson|one\ pair|orangutan|orchestra|own\ goal|pantomime|paperback|partition|pedometer|pen\ name|penthouse|pepperoni|permanent|petticoat|phenazine|pheromone|phosphine|phthalein|pineapple|pistachio|polyester|polygraph|polynosic|porphyrin|portfolio|processor|projector|pronghorn|propylene|pteridine|quarterly|quidditch|quinoline|racetrack|raspberry|repertory|saccharin|sacrament|sandpaper|saxophone|saxophone|saxophone|schnauzer|scrapbook|sea\ bass|semicolon|set\ list|shareware|sharpener|shortstop|sign\-off|silk\ hat|situation|ski\ lift|skydiving|snowboard|softcover|spaghetti|spaghetti|spokesman|spotlight|sprinkler|stainless|stopwatch|streaking|stretcher|stun\ gun|sulfoxide|superhero|surfboard|sweatsuit|symposium|tank\ top|technical|telepathy|telephone|terrorism|terrorist|thiophene|three\ Rs|thumbnail|timesheet|touchdown|toughness|trackback|treadmill|triathlon|tropylium|tube\ top|two\ pair|uninstall|vegetable|videotape|voicemail|wonderful|woodchuck|workspace|wrestling|Arkansas|Balinese|Bismarck|Brooklyn|Calcutta|Cambodia|Carlisle|Catholic|Caucasus|Cheshire|Cheyenne|Colorado|Columbia|Columbus|Cornwall|Damascus|Delaware|Duckburg|Ethernet|Eurobeat|Ferguson|Florence|Hartford|Hogwarts|Illinois|Interpol|Japanese|Kentucky|Kingston|Kiribati|Labrador|Limerick|Malaysia|Manitoba|Maryland|McDonald|Michigan|Missouri|Monopoly|Montreal|Nebraska|Oklahoma|Pekinese|Pentagon|Piedmont|Richmond|Sanskrit|Scotland|Siberian|Slovakia|Superman|Syracuse|Tasmania|Victoria|Virginia|YouTuber|aardwolf|accident|acridine|actinoid|aerobics|aircheck|aldehyde|allegory|alphabet|amethyst|ammonite|animator|antelope|aquacise|artifact|asterisk|aye\-aye|barbecue|baseball|biathlon|billiard|bob\ cut|bodysuit|bookmark|bracelet|broccoli|building|caffeine|calendar|camisole|campaign|campfire|camphane|camphene|campsite|carbonyl|carboxyl|cardigan|carotene|cashmere|chainsaw|champion|clarinet|cocktail|computer|consumer|continue|corduroy|cosecant|cracking|creative|creature|cyclamen|database|deadball|delivery|designer|diskette|doo\-wop|dopamine|download|dressing|dumbbell|dynamite|dyslexia|earphone|effector|emulator|epilogue|ethylene|europium|exbibyte|fastback|feedback|fellatio|feminism|feminist|firewall|firmware|flamingo|fluorene|football|forkball|forklift|freeware|friendly|fructose|fuckin\’|gargoyle|gibibyte|glycerin|glycerol|graphics|gumption|handball|hardware|hazelnut|hedonism|homeroom|hot\ dog|hotplate|ice\ bar|identity|indazole|interior|internet|inverter|joystick|juggling|kangaroo|keyboard|keyframe|kibibyte|kickball|kinkajou|lacrosse|lifework|limonene|liniment|lipstick|literacy|lobbying|lobbyist|lollipop|lossless|lovebird|macaroni|mandrill|manicure|marathon|marzipan|meatball|mebibyte|mechanic|mechanic|minutiae|mistress|moonroof|motorcar|mulligan|mushroom|musician|nanotech|navigate|necklace|neutrino|newcomer|newsroom|nickname|nihonium|no\ pair|no\-show|nonsense|notebook|overdose|overtime|oxytocin|parabola|parallel|particle|passport|password|pebibyte|pedicure|plankton|platform|playlist|plug\-in|ponytail|porridge|portrait|powerful|prescore|pressure|princess|property|protease|pyrazine|pyrazole|pyridine|radiator|raincoat|reaction|recorder|recorder|remember|resource|response|revolver|rhapsody|romantic|roommate|sabotage|sabotage|sadistic|salesman|sandwich|sapphire|sapphism|sapphism|scenario|sentence|serenade|shortcut|showcase|shredder|shutdown|skinhead|softball|software|spanking|spelling|stocking|straight|stripper|stuntman|sundress|sunglass|suspense|swimming|symphony|tea\ bag|teaspoon|tebibyte|teleport|teletype|template|terminal|textbook|thiazine|thiazole|thriller|timeline|top\ hat|touchpad|trackpad|trombone|tungsten|tutorial|twintail|typeface|vanadium|vibrator|waitress|wallaroo|win\-win|workshop|wormhole|wrapping|wrestler|xanthene|yobibyte|zebibyte|Alabama|Aladdin|Alberta|Algeria|Alucard|America|Arizona|Atlanta|Augusta|Austria|Baghdad|Bangkok|Barbuda|Bermuda|Bigfoot|Bitcoin|Britain|Buffalo|Burbank|Burmese|Calicut|Cardiff|Chicago|Concord|Cumbria|Denmark|Detroit|Dracula|England|Estonia|Eurasia|Finland|Florida|Frisbee|Georgia|Germany|Glasgow|Honiara|Houston|Hungary|Iceland|Indiana|Iqaluit|Ireland|Jackson|Jamaica|Jessica|Kennedy|Lansing|Lebanon|Lincoln|Lucifer|Madison|Maglite|Maltese|Mercury|Messiah|Montana|Myanmar|Nigeria|Norwich|Oceania|Olympia|Olympic|Ontario|Orlando|Orleans|Patrick|Pegasus|Prussia|Puritan|Ragdoll|Raleigh|Reading|Rumania|Sealand|Seattle|Sindbad|Solomon|Somalia|Swansea|Toronto|Trenton|Unicode|Vermont|Vietnam|Warwick|academy|acrobat|ad\-lib|advisor|albumin|alumina|amazing|amidine|anagram|antenna|arcsine|asphalt|aurochs|avocado|azulene|backing|bagpipe|barcode|batiste|batsman|battery|benzene|bismuth|blanket|bloomer|bookend|bourbon|bowling|bracket|breaker|browser|burning|cabaret|cabbage|camping|captain|caramel|caravan|casting|catalog|catcher|cathode|channel|chariot|cheetah|choline|chowder|coaster|complex|context|corsage|costume|counter|counter|cricket|cupcake|curling|curtain|cycloid|cyclops|darling|default|desktop|dessert|dextrin|diagram|diagram|diamond|dilemma|dubbing|dubstep|earring|emerald|enchant|episode|epsilon|exbibit|failure|fascism|fascist|fashion|fencing|fermion|fermium|fiction|fighter|flannel|formant|fritter|fuchsia|furazan|gallery|gallium|gazelle|general|gibibit|gingham|glucose|gorilla|granola|graphic|gravure|grizzly|hairnet|hairpin|hamster|handbag|heading|headset|heroine|heroism|holmium|holster|hostess|hotcake|husband|install|instant|invoice|jasmine|jogging|jukebox|kerning|ketchup|kibibit|kickoff|lactose|latency|leisure|lemming|leotard|lesbian|lettuce|library|lighter|lithium|lockout|lowbrow|malaria|malware|mammoth|manager|manatee|manhole|mansion|marimba|mascara|measure|mebibit|meerkat|merfolk|mermaid|methane|midriff|miracle|monocle|monsoon|monster|muffler|mustang|mustard|naphtha|narcist|neoteny|netizen|network|nitrile|oatmeal|obelisk|omicron|on\ air|opossum|organdy|osazone|ottoman|overall|oxazole|paisley|palmtop|pancake|panpipe|passing|pebibit|peccary|pelican|penguin|peptide|peridot|pharaoh|phoenix|pianist|piccolo|pilates|pitcher|placebo|podcast|pop\-up|porphin|portion|pretzel|printer|privacy|program|propose|protein|psychic|pudding|pumpkin|punkish|pyramid|pyrrole|quality|quarter|quinone|railgun|rampway|rebrand|receipt|recruit|renewal|replica|request|romanji|sandbag|sausage|scandal|science|scooter|seafood|seminar|service|shelter|shotgun|shuffle|slipper|sneaker|soliton|sorcery|spandex|spangle|spangle|special|sponsor|spyware|stadium|stalker|stapler|station|stearin|steroid|steward|storage|stretch|sulfone|surfing|sweater|synapse|tabloid|tachyon|taffeta|tamarin|tangent|tankini|tapping|tardyon|tebibit|tension|terpene|terrier|timpani|toaster|tooltip|topless|topping|tornado|tractor|traffic|trailer|trainer|trigger|tritium|trouble|unicorn|uniform|upsilon|upsilon|uptempo|vanitas|vehicle|vitamin|vitriol|vocoder|wallaby|website|winglet|yobibit|zebibit|Adidas|Alaska|Albany|Argyll|Asgard|Austin|Batman|Bengal|Berlin|Birman|Bissau|Bombay|Brazil|Cairns|Canada|Canton|Carson|Creole|Cymric|Dakota|Denver|Dundee|Fergus|France|Fresno|Gambia|Google|Gotham|Guinea|Harlem|Hawaii|Helena|Hessen|Hobart|Jersey|Juneau|Kansas|Klaxon|Kodiak|Lolita|London|Madrid|Majuro|Mexico|Moscow|Naples|Nazism|Nessie|Nevada|Newfie|Norway|Ocicat|Ottawa|Persia|Pierre|Poland|Pomona|Quaker|Queens|Reebok|Saturn|Somali|Sufism|Sunday|Sweden|Sydney|Topeka|Torbay|Tucson|Venice|Venice|Vienna|Viking|acacia|accent|advice|akimbo|albedo|alcove|alkane|alkene|alkyne|almond|ampere|anklet|arsine|aurora|autumn|avatar|ballad|bangle|banker|banner|baobab|baryon|batter|beagle|beaver|beluga|bikini|bishop|bitmap|blazar|blazer|blouse|bluesy|bobcat|booing|bookie|bowler|bowtie|boxing|boyish|breast|bridge|broker|brooch|brunch|burger|bustle|butter|campus|cannon|canvas|carane|career|carhop|caster|caviar|cement|center|chance|change|cheese|cinque|circus|closet|cobalt|coffee|comedy|cookie|cooler|corset|cosine|cotton|couple|course|credit|cubism|cursor|cyborg|cymbal|daemon|dealer|deejay|deejay|denier|design|digest|dirndl|domain|doping|double|dragon|driver|eggnog|encore|engine|escape|ethene|ethyne|expert|factor|fanart|fanfic|fennec|ferret|figure|floppy|folder|fondue|fourth|freeze|garage|garnet|gender|giga\-|girdle|goblin|goggle|gotcha|gramme|guinea|guitar|haboob|hacker|hammer|hanger|health|helium|helmet|heroic|hijack|hockey|horror|hotkey|huddle|hyphen|indene|indole|jackal|jaguar|jersey|jingle|jockey|jungle|kelvin|kernel|keyman|kipper|lagoon|lambda|laptop|layout|leader|lepton|let\'s|letter|lizard|loafer|locker|lonely|lotion|lounge|louver|makeup|mallet|margay|marker|marmot|mascot|master|memory|memory|mobile|modern|module|monkey|mosque|muffin|napkin|nekton|neuron|newton|nigger|nipper|normal|occult|ocelot|office|olefin|orgasm|papaya|parity|parody|parsec|parser|pastel|patrol|peanut|phenol|phonon|picene|pidgin|pinene|pistol|piston|plasma|plough|pocket|polish|pompon|poodle|poster|potato|pretty|prince|pterin|public|pulsar|purine|puzzle|quasar|racket|raisin|ranger|recipe|record|reggae|reject|repeat|review|rocket|router|ruffle|sadism|sadist|safari|salmon|sambar|sandal|saucer|scalar|scanty|scarab|scheme|school|script|secant|second|seesaw|selfie|sensor|serval|shadow|sherry|shorts|shovel|shovel|silage|single|siphon|sister|skiing|slacks|sleeve|slider|soccer|sonnet|speech|sphinx|spring|sprint|squall|static|street|stress|studio|summer|suplex|surfer|tablet|talkie|teacup|tennis|thread|ticket|ticket|tissue|toilet|tomato|trance|trauma|treble|trophy|trunks|tunnel|turkey|tuxedo|typing|upload|utopia|versus|violin|waffle|waiter|weekly|whisky|window|window|winter|wizard|wombat|wrench|writer|wyvern|yellow|yo\-yo|zombie|Abuja|Atari|Boise|Chris|Cupid|Delhi|Devon|Diana|Dover|Flint|Goofy|Haiti|Helen|Idaho|Italy|Japan|Korat|LASIK|Macao|Malay|Nevis|Niger|Obama|Oscar|Papua|Paris|Pence|Qatar|Salem|Santa|Spain|Texas|Tibet|Wales|about|agent|alibi|alien|alpha|amine|amino|angle|anode|apron|auxin|azole|bagel|banjo|bench|bingo|bison|bitch|black|blind|blues|bonus|booth|boots|boson|boxer|brain|brief|bugle|cable|caddy|cairn|cameo|candy|canon|carol|cater|cello|champ|cheap|chess|cigar|clean|clear|clone|coach|cobra|cocoa|colon|comic|comma|couch|cover|crane|crank|curry|dates|decoy|delta|denim|deuce|devil|diode|dirty|donut|drain|dress|drill|dryad|dummy|dwarf|easel|eight|error|esper|ethos|event|farad|fence|ferry|first|flash|frame|frill|fruit|gamma|ganja|gluon|gnome|goods|graph|gravy|group|guard|guava|happy|heart|henry|homer|honey|hotel|house|husky|hydra|hyena|icing|irony|jeans|joker|joule|juice|kappa|kayak|kazoo|kerma|keton|kiosk|knife|knock|lapel|laser|layer|lemon|liger|lilac|limbo|lipid|looks|lotto|lucky|lumen|lunch|luxon|lynch|lyric|magma|magus|mango|merge|meter|mocap|modem|money|moped|motel|mouse|naive|night|noise|nylon|nymph|ocean|omega|onium|owner|oxime|panda|pansy|pants|panty|paper|parka|party|peace|peach|pearl|penny|piano|pinch|pitch|pixel|plane|plane|plier|poker|polio|porch|power|print|prune|pumps|punch|purse|putty|pygmy|pylon|pyran|quark|quark|queen|query|quilt|radar|radio|range|rayon|relax|remix|rider|right|rival|rivet|robot|roger|rough|ruble|rugby|salad|sales|salsa|scale|scion|scoop|scout|scrap|serif|seven|sharp|shawl|shell|shift|shirt|shoes|short|shred|sigma|siren|skier|skirt|skort|skunk|slash|slide|slime|slump|smart|smile|snack|snood|sonar|spade|speed|spell|spoon|staff|stand|steak|stick|stick|study|stunt|style|sylph|sysop|tenor|tesla|theta|third|three|tiara|tigon|title|toast|token|topic|totem|trend|trick|truck|trump|trust|tulip|tunic|ultra|vault|viral|virus|voice|waltz|watch|water|water|white|winch|yacht|Bill|Cuba|GABA|Gore|Iowa|Lima|Luke|Manx|Mars|NASA|Nike|Nile|Odin|Ohio|Oslo|Peru|Pest|Puma|Troy|Utah|York|acyl|ally|anal|anoa|atom|baby|ball|base|beam|belt|beta|blue|bolt|bowl|byte|cage|cake|camp|card|case|cell|chat|club|coat|coin|cone|cool|core|czar|data|deck|desk|dirt|dodo|doll|dome|door|duct|euro|fall|feet|felt|file|five|flag|flag|flip|foot|fork|four|fuck|full|fuse|gaff|game|gate|ghee|goal|golf|gong|gown|grey|hair|half|harp|hero|high|hint|home|hood|host|hunt|icon|idol|info|iron|iron|item|jack|jazz|jeep|jump|king|kiss|knot|lace|lady|lamp|lard|left|life|lift|lime|line|link|lion|lisp|live|love|lynx|maid|mail|main|mana|mask|meme|mill|mime|mini|mink|mint|moon|mule|muon|muse|mute|name|news|nice|nine|note|oboe|ogre|over|ovum|page|pair|pass|pawn|pica|pick|pink|pint|pipe|play|play|polo|pony|puma|punt|pure|quiz|rape|rare|reel|ring|ruby|ruby|sack|safe|sand|seal|seat|sexy|ship|shop|sice|silo|sine|skin|slip|slum|slur|soca|sofa|soft|song|soul|soup|star|stew|stop|suit|suit|swan|temp|text|tire|tong|tour|tram|tray|tray|tree|tuba|turn|unit|watt|wear|wife|wine|wink|wolf|worm|yogi|zebu|zeta)(ed|es|d|s)?(\W|$)/gi;
const jpMap = {
  "aardwolf": "アードウルフ",
  "about": "アバウト",
  "abuja": "アブジャ",
  "abyssinian": "アビシニアン",
  "acacia": "アケイシャ",
  "academy": "アカデミー",
  "accent": "アクセント",
  "accident": "アクシデント",
  "accordion": "アコーディオン",
  "acenaphthene": "アセナフテン",
  "acetylene": "アセチレン",
  "acoustic guitar": "アコースティック・ギター",
  "acridine": "アクリジン",
  "acrobat": "アクロバット",
  "actinoid": "アクチノイド",
  "action game": "アクションゲーム",
  "acyl": "アシル",
  "ad-lib": "アドリブ",
  "adidas": "アディダス",
  "adrenaline": "アドレナリン",
  "adventure": "アドベンチャー",
  "advice": "アドバイス",
  "advisor": "アドバイザー",
  "aerobics": "エアロビクス",
  "afterburner": "アフターバーナー",
  "afternoon tea": "アフタヌーンティー",
  "agent": "エージェント",
  "air compressor": "エアコンプレッサー",
  "air conditioner": "エアコンディショナー",
  "air guitar": "エアギター",
  "aircheck": "エアチェック",
  "akimbo": "アキンボ",
  "alabama": "アラバマ",
  "alabaster": "アラバスター",
  "aladdin": "アラジン",
  "alaska": "アラスカ",
  "albany": "オールバニ",
  "albedo": "アルベド",
  "alberta": "アルバータ",
  "albumin": "アルブミン",
  "albuquerque": "アルバカーキ",
  "alcove": "アルコーブ",
  "aldehyde": "アルデヒド",
  "alexander": "アレクサンダー",
  "alexandrite": "アレキサンドライト",
  "algeria": "アルジェリア",
  "algorithm": "アルゴリズム",
  "ali baba": "アリババ",
  "alibi": "アリバイ",
  "alien": "エイリアン",
  "alkane": "アルカン",
  "alkene": "アルケン",
  "alkyne": "アルキン",
  "allegory": "アレゴリー",
  "alligator": "アリゲーター",
  "ally": "アライ",
  "almond": "アーモンド",
  "alpha": "アルファ",
  "alphabet": "アルファベット",
  "alucard": "アルカード",
  "alumina": "アルミナ",
  "amanuensis": "アマヌンシス",
  "amazing": "アメージング",
  "america": "アメリカ",
  "american curl": "アメリカンカール",
  "american football": "アメリカンフットボール",
  "american shorthair": "アメリカン・ショートヘア",
  "american wirehair": "アメリカンワイヤーヘア",
  "amethyst": "アメシスト",
  "amidine": "アミジン",
  "amine": "アミン",
  "amino": "アミノ",
  "ammonite": "アンモナイト",
  "ampere": "アンペア",
  "ampersand": "アンパサンド",
  "anagram": "アナグラム",
  "anal": "アナル",
  "anal sex": "アナルセックス",
  "anarchism": "アナキズム",
  "anarchist": "アナキスト",
  "anchorage": "アンカレッジ",
  "angle": "アングル",
  "animation": "アニメーション",
  "animation studio": "アニメーションスタジオ",
  "animator": "アニメーター",
  "anklet": "アンクレット",
  "annapolis": "アナポリス",
  "announcer": "アナウンサー",
  "anoa": "アノア",
  "anode": "アノード",
  "antelope": "アンテロープ",
  "antenna": "アンテナ",
  "anthracene": "アントラセン",
  "anti-alias": "アンチエイリアス",
  "apostrophe": "アポストロフィー",
  "appliance": "アプライアンス",
  "application": "アプリケーション",
  "apron": "エプロン",
  "aqua walking": "アクアウオーキング",
  "aquacise": "アクアサイズ",
  "aquamarine": "アクアマリン",
  "arccosine": "アークコサイン",
  "arccotangent": "アークコタンジェント",
  "arcsine": "アークサイン",
  "arctangent": "アークタンジェント",
  "arena football": "アリーナフットボール",
  "argyll": "アーガイル",
  "arizona": "アリゾナ",
  "arkansas": "アーカンソー",
  "arm wrestling": "アームレスリング",
  "arsine": "アルシン",
  "artichoke": "アーティチョーク",
  "artifact": "アーティファクト",
  "artist-in-residence": "アーティストインレジデンス",
  "asceticism": "アセティシズム",
  "ascii art": "アスキーアート",
  "asgard": "アスガード",
  "asparagine": "アスパラギン",
  "asparagus": "アスパラガス",
  "asphalt": "アスファルト",
  "assault rifle": "アサルトライフル",
  "assistant": "アシスタント",
  "assistant director": "アシスタントディレクター",
  "associate": "アソシエイト",
  "association football": "アソシエーション・フットボール",
  "asterisk": "アスタリスク",
  "astroturf": "アストロターフ",
  "atari": "アタリ",
  "atlanta": "アトランタ",
  "atlantic city": "アトランティックシティ",
  "atom": "アトム",
  "audio commentary": "オーディオコメンタリー",
  "augusta": "オーガスタ",
  "aurochs": "オーロックス",
  "aurora": "オーロラ",
  "austin": "オースティン",
  "australia": "オーストラリア",
  "austria": "オーストリア",
  "austria-hungary": "オーストリア゠ハンガリー",
  "autobicycle": "オートバイシクル",
  "autopilot": "オートパイロット",
  "autumn": "オータム",
  "auxin": "オーキシン",
  "avatar": "アバター",
  "avocado": "アボカド",
  "aye-aye": "アイアイ",
  "azetidine": "アゼチジン",
  "azole": "アゾール",
  "azulene": "アズレン",
  "baby": "ベビー",
  "baby boom": "ベビーブーム",
  "baby boomer": "ベビーブーマー",
  "baby doll": "ベビードール",
  "babylonia": "バビロニア",
  "backing": "バッキング",
  "badminton": "バドミントン",
  "bagel": "ベーグル",
  "baghdad": "バグダッド",
  "bagpipe": "バグパイプ",
  "balinese": "バリニーズ",
  "ball": "ボール",
  "ball game": "ボールゲーム",
  "ball pen": "ボールペン",
  "ballad": "バラード",
  "bangkok": "バンコク",
  "bangladesh": "バングラデシュ",
  "bangle": "バングル",
  "banjo": "バンジョー",
  "banker": "バンカー",
  "banner": "バナー",
  "baobab": "バオバブ",
  "barbecue": "バーベキュー",
  "barbuda": "バーブーダ",
  "barcode": "バーコード",
  "barrier-free": "バリアフリー",
  "baryon": "バリオン",
  "base": "ベース",
  "base coat": "ベースコート",
  "baseball": "ベースボール",
  "basketball": "バスケットボール",
  "bass drum": "バスドラム",
  "bath towel": "バスタオル",
  "batiste": "バチスト",
  "batman": "バットマン",
  "batsman": "バッツマン",
  "batter": "バッター",
  "battery": "バッテリー",
  "battle rifle": "バトルライフル",
  "beach sandal": "ビーチサンダル",
  "beach towel": "ビーチタオル",
  "beagle": "ビーグル",
  "beam": "ビーム",
  "beaver": "ビーバー",
  "beefsteak": "ビーフステーキ",
  "belt": "ベルト",
  "belt conveyor": "ベルトコンベア",
  "beluga": "ベルーガ",
  "bench": "ベンチ",
  "bengal": "ベンガル",
  "benzene": "ベンゼン",
  "berberine": "ベルベリン",
  "berlin": "バーリン",
  "bermuda": "バミューダ",
  "berwick-upon-tweed": "ベリック・アポン・ツイード",
  "beryllium": "ベリリウム",
  "beta": "ベータ",
  "beverly hills": "ビバリーヒルズ",
  "biathlon": "バイアスロン",
  "big bang": "ビッグバン",
  "bigfoot": "ビッグフット",
  "bikini": "ビキニ",
  "bill": "ビル",
  "billiard": "ビリヤード",
  "bingo": "ビンゴ",
  "birdwatching": "バードウォッチング",
  "birman": "バーマン",
  "bishop": "ビショップ",
  "bismarck": "ビスマーク",
  "bismuth": "ビスマス",
  "bison": "バイソン",
  "bisque doll": "ビスクドール",
  "bissau": "ビサウ",
  "bitch": "ビッチ",
  "bitcoin": "ビットコイン",
  "bitmap": "ビットマップ",
  "black": "ブラック",
  "black bass": "ブラックバス",
  "black friday": "ブラックフライデー",
  "black hole": "ブラックホール",
  "blackberry": "ブラックベリー",
  "blackjack": "ブラックジャック",
  "blanket": "ブランケット",
  "blazar": "ブレーザー",
  "blazer": "ブレザー",
  "blind": "ブラインド",
  "bloomer": "ブルマー",
  "blouse": "ブラウス",
  "blue": "ブルー",
  "blue hawaii": "ブルーハワイ",
  "blueberry": "ブルーベリー",
  "blues": "ブルース",
  "bluesy": "ブルージー",
  "bluetooth": "ブルートゥース",
  "board game": "ボードゲーム",
  "boarding school": "ボーディングスクール",
  "bob cut": "ボブカット",
  "bobblehead": "ボブルヘッド",
  "bobcat": "ボブキャット",
  "bodysuit": "ボディスーツ",
  "boise": "ボイシ",
  "bolt": "ボルト",
  "bombay": "ボンベイ",
  "bonus": "ボーナス",
  "booing": "ブーイング",
  "bookend": "ブックエンド",
  "bookie": "ブッキー",
  "bookmaker": "ブックメーカー",
  "bookmark": "ブックマーク",
  "boomerang": "ブーメラン",
  "booth": "ブース",
  "boots": "ブーツ",
  "boson": "ボソン",
  "bottle cage": "ボトルケージ",
  "bottle cap": "ボトルキャップ",
  "bottle green": "ボトルグリーン",
  "bourbon": "バーボン",
  "bournemouth": "ボーンマス",
  "bowl": "ボウル",
  "bowler": "ボウラー",
  "bowling": "ボウリング",
  "bowling ball": "ボウリングボール",
  "bowtie": "ボウタイ",
  "boxer": "ボクサー",
  "boxing": "ボクシング",
  "boxing glove": "ボクシンググローブ",
  "boyfriend": "ボーイフレンド",
  "boyish": "ボーイッシュ",
  "bracelet": "ブレスレット",
  "bracket": "ブラケット",
  "brain": "ブレーン",
  "brainstorming": "ブレインストーミング",
  "brassiere": "ブラジャー",
  "brazil": "ブラジル",
  "brazil nut": "ブラジルナッツ",
  "breakdance": "ブレークダンス",
  "breaker": "ブレーカー",
  "breast": "ブレスト",
  "bridge": "ブリッジ",
  "bridgeport": "ブリッジポート",
  "brief": "ブリーフ",
  "brightness": "ブライトネス",
  "britain": "ブリテン",
  "british columbia": "ブリティッシュコロンビア",
  "british shorthair": "ブリティッシュショートヘア",
  "broccoli": "ブロッコリー",
  "broker": "ブローカー",
  "brooch": "ブローチ",
  "brooklyn": "ブルックリン",
  "browser": "ブラウザ",
  "brunch": "ブランチ",
  "buffalo": "バッファロー",
  "bugle": "ビューグル",
  "building": "ビルディング",
  "bulldozer": "ブルドーザー",
  "bungee jump": "バンジージャンプ",
  "burbank": "バーバンク",
  "burger": "バーガー",
  "burmese": "バーミーズ",
  "burning": "バーニング",
  "bush dog": "ブッシュドッグ",
  "business class": "ビジネスクラス",
  "bustle": "バッスル",
  "butter": "バター",
  "butterfly": "バタフライ",
  "byte": "バイト",
  "byzantine": "ビザンティン",
  "bâton-rouge": "バトンルージュ",
  "cabaret": "キャバレー",
  "cabbage": "キャベツ",
  "cabin attendant": "キャビンアテンダント",
  "cable": "ケーブル",
  "cable network": "ケーブルネットワーク",
  "cable television": "ケーブルテレビ",
  "caddy": "キャディー",
  "caernarfon": "カーナーヴォン",
  "cafe a la creme": "カフェアラクレーム",
  "caffeine": "カフェイン",
  "cage": "ケージ",
  "cairn": "ケアン",
  "cairns": "ケアンズ",
  "cake": "ケーキ",
  "calcutta": "カルカッタ",
  "calendar": "カレンダー",
  "calicut": "カリカット",
  "california": "カリフォルニア",
  "calligraphy": "カリグラフィー",
  "cambodia": "カンボジア",
  "cambridge": "ケンブリッジ",
  "cameo": "カメオ",
  "cameraman": "キャメラマン",
  "camerawork": "カメラワーク",
  "camisole": "キャミソール",
  "camouflage": "カモフラージュ",
  "camp": "キャンプ",
  "campaign": "キャンペーン",
  "campfire": "キャンプファイヤー",
  "camphane": "カンファン",
  "camphene": "カンフェン",
  "camping": "キャンピング",
  "campsite": "キャンプサイト",
  "campus": "キャンパス",
  "canada": "カナダ",
  "canadian dollar": "カナダドル",
  "canadian football": "カナディアンフットボール",
  "canadian football league": "カナディアンフットボールリーグ",
  "candy": "キャンディ",
  "candy bar": "キャンディーバー",
  "candy cane": "キャンディーケイン",
  "cannibalism": "カニバリズム",
  "cannon": "キャノン",
  "canon": "カノン",
  "canton": "カントン",
  "canvas": "キャンバス",
  "capsaicin": "カプサイシン",
  "captain": "キャプテン",
  "caramel": "キャラメル",
  "carane": "カラン",
  "caravan": "キャラバン",
  "carbazole": "カルバゾール",
  "carboline": "カルボリン",
  "carbonyl": "カルボニル",
  "carboxyl": "カルボキシル",
  "carbylamine": "カルビルアミン",
  "card": "カード",
  "card game": "カードゲーム",
  "cardiff": "カーディフ",
  "cardigan": "カーディガン",
  "career": "キャリア",
  "careerwoman": "キャリアウーマン",
  "carhop": "カーホップ",
  "carlisle": "カーライル",
  "carol": "キャロル",
  "carotene": "カロテン",
  "carotenoid": "カロテノイド",
  "carson": "カーソン",
  "carson city": "カーソンシティ",
  "case": "ケース",
  "cash dispenser": "キャッシュディスペンサー",
  "cashmere": "カシミア",
  "caster": "キャスター",
  "casting": "キャスティング",
  "cat's eye": "キャッツアイ",
  "catalog": "カタログ",
  "catastrophe": "カタストロフィ",
  "catcher": "キャッチャー",
  "cater": "ケイト",
  "cathode": "カソード",
  "catholic": "カソリック",
  "caucasus": "コーカサス",
  "cauliflower": "カリフラワー",
  "caviar": "キャビア",
  "cayman brac": "ケイマンブラック",
  "celebrity": "セレブリティ",
  "cell": "セル",
  "cello": "チェロ",
  "celluloid": "セルロイド",
  "cement": "セメント",
  "center": "センター",
  "chain mail": "チェーンメール",
  "chainsaw": "チェーンソー",
  "chairlift": "チェアリフト",
  "challenge": "チャレンジ",
  "chameleon": "カメレオン",
  "champ": "チャンプ",
  "champagne": "シャンペン",
  "champaign": "シャンペーン",
  "champion": "チャンピオン",
  "championship": "チャンピオンシップ",
  "chance": "チャンス",
  "chandelier": "シャンデリア",
  "change": "チェンジ",
  "channel": "チャンネル",
  "chariot": "チャリオット",
  "charleston": "チャールストン",
  "charlottesville": "シャーロッツビル",
  "chartreux": "シャルトリュー",
  "chat": "チャット",
  "chattanooga": "チャタヌーガ",
  "cheap": "チープ",
  "check-in": "チェックイン",
  "cheerleader": "チアリーダー",
  "cheerleading": "チアリーディング",
  "cheese": "チーズ",
  "cheese fondue": "チーズフォンデュ",
  "cheeseburger": "チーズバーガー",
  "cheesecake": "チーズケーキ",
  "cheetah": "チーター",
  "cherry tomato": "チェリートマト",
  "cheshire": "チェシャー",
  "chess": "チェス",
  "chesterfield": "チェスターフィールド",
  "chesterfield coat": "チェスターフィールドコート",
  "chewing gum": "チューインガム",
  "cheyenne": "シャイアン",
  "chicago": "シカゴ",
  "chicken nugget": "チキン・ナゲット",
  "chimera, chimera": "キメラ",
  "chimpanzee": "チンパンジー",
  "chinchilla": "チンチラ",
  "chiropractor": "カイロプラクター",
  "chlorophyll": "クロロフィル",
  "chocolate": "チョコレート",
  "choline": "コリン",
  "chow chow": "チャウ・チャウ",
  "chowder": "チャウダー",
  "chris": "クリス",
  "christian": "クリスチャン",
  "christmas": "クリスマス",
  "christmas tree": "クリスマスツリー",
  "chromakey": "クロマキー",
  "cigar": "シガー",
  "cigarette": "シガレット",
  "cincinnati": "シンシナティ",
  "cinnoline": "シンノリン",
  "cinque": "シンク",
  "circus": "サーカス",
  "clarinet": "クラリネット",
  "clean": "クリーン",
  "cleansing": "クレンジング",
  "clear": "クリア",
  "cleveland": "クリーブランド",
  "clipboard": "クリップボード",
  "clock radio": "クロックラジオ",
  "clone": "クローン",
  "closet": "クローゼット",
  "club": "クラブ",
  "coach": "コーチ",
  "coaster": "コースター",
  "coat": "コート",
  "coatdress": "コートドレス",
  "cobalt": "コバルト",
  "cobra": "コブラ",
  "coca-cola": "コカコーラ",
  "cocktail": "カクテル",
  "cocktail dress": "カクテルドレス",
  "cocktail party": "カクテルパーティー",
  "cocktail sauce": "カクテルソース",
  "cocoa": "ココア",
  "coconut oil": "ココナッツオイル",
  "coelacanth": "シーラカンス",
  "coffee": "コーヒー",
  "coffee mill": "コーヒーミル",
  "coffeemaker": "コーヒーメーカー",
  "coin": "コイン",
  "coin toss": "コイントス",
  "collaboration": "コラボレーション",
  "collection": "コレクション",
  "college football": "カレッジフットボール",
  "colon": "コロン",
  "color television": "カラーテレビ",
  "colorado": "コロラド",
  "columbia": "コロンビア",
  "columbus": "コロンバス",
  "combination": "コンビネーション",
  "comedy": "コメディ",
  "comedy club": "コメディクラブ",
  "comic": "コミック",
  "coming out": "カミングアウト",
  "comma": "コンマ",
  "commissioner": "コミッショナー",
  "compact disc": "コンパクトディスク",
  "complex": "コンプレックス",
  "component": "コンポーネント",
  "computer": "コンピューター",
  "computer game": "コンピュータゲーム",
  "computerization": "コンピュータリゼーション",
  "computing": "コンピューティング",
  "concord": "コンコード",
  "condenser": "コンデンサ",
  "cone": "コーン",
  "connecticut": "コネチカット",
  "consensus": "コンセンサス",
  "constantinople": "コンスタンティノープル",
  "consumer": "コンシューマー",
  "contact lens": "コンタクトレンズ",
  "context": "コンテキスト",
  "continue": "コンティニュー",
  "continuity": "コンティニュイティ",
  "convertible": "コンバーチブル",
  "cookie": "クッキー",
  "cool": "クール",
  "cooler": "クーラー",
  "copenhagen": "コペンハーゲン",
  "coptisine": "コプチシン",
  "corduroy": "コーデュロイ",
  "core": "コア",
  "corkscrew": "コルクスクリュー",
  "corn flake": "コーンフレーク",
  "corn syrup": "コーンシロップ",
  "cornish rex": "コーニッシュレックス",
  "cornwall": "コーンウォール",
  "corporate identity": "コーポレートアイデンティティ",
  "corsage": "コサージュ",
  "corset": "コルセット",
  "cosecant": "コセカント",
  "cosine": "コサイン",
  "costume": "コスチューム",
  "cotangent": "コタンジェント",
  "cotton": "コットン",
  "couch": "カウチ",
  "counter": "カウンタ",
  "countertenor": "カウンターテナー",
  "couple": "カップル",
  "course": "コース",
  "cover": "カバー",
  "cracking": "クラッキング",
  "cranberry": "クランベリー",
  "crane": "クレーン",
  "crank": "クランク",
  "creative": "クリエイティブ",
  "creature": "クリーチャー",
  "credit": "クレジット",
  "credit card": "クレジットカード",
  "creole": "クレオール",
  "cricket": "クリケット",
  "crinoline": "クリノリン",
  "crossover": "クロスオーバー",
  "crossword": "クロスワード",
  "crossword puzzle": "クロスワードパズル",
  "cuba": "キューバ",
  "cubism": "キュービズム",
  "cumbria": "カンブリア",
  "cupcake": "カップケーキ",
  "cupid": "キューピッド",
  "curling": "カーリング",
  "curly hair": "カーリーヘア",
  "curriculum": "カリキュラム",
  "curry": "カレー",
  "cursor": "カーソル",
  "curtain": "カーテン",
  "custard pudding": "カスタードプディング",
  "cybernetics": "サイバネティックス",
  "cyborg": "サイボーグ",
  "cyclamen": "シクラメン",
  "cycloid": "サイクロイド",
  "cyclops": "サイクロプス",
  "cymbal": "シンバル",
  "cymric": "キムリック",
  "czar": "ツァー",
  "czechoslovakia": "チェコスロバキア",
  "daemon": "デーモン",
  "daisy duck": "デイジーダック",
  "dakota": "ダコタ",
  "dalmatian": "ダルメシアン",
  "damascus": "ダマスカス",
  "dangerous": "デンジャラス",
  "dark matter": "ダークマター",
  "darling": "ダーリン",
  "dashboard": "ダッシュボード",
  "data": "データ",
  "data mining": "データマイニング",
  "database": "データベース",
  "dates": "デーツ",
  "deadball": "デッドボール",
  "dealer": "ディーラー",
  "debit card": "デビットカード",
  "deck": "デッキ",
  "decoration": "デコレーション",
  "decoy": "デコイ",
  "dedication": "デディケーション",
  "deejay": "ディージェー",
  "deep fryer": "ディープフライヤー",
  "deep kiss": "ディープ・キス",
  "default": "デフォルト",
  "deflation": "デフレーション",
  "delaware": "デラウェア",
  "delaware city": "デラウェアシティ",
  "delhi": "デリー",
  "delivery": "デリバリー",
  "delta": "デルタ",
  "denier": "デニール",
  "denim": "デニム",
  "denmark": "デンマーク",
  "dental floss": "デンタルフロス",
  "denver": "デンバー",
  "department store": "デパートメントストア",
  "derivative": "デリバティブ",
  "des moines": "デモイン",
  "design": "デザイン",
  "designer": "デザイナー",
  "desk": "デスク",
  "desktop": "デスクトップ",
  "desktop publishing": "デスクトップパブリッシング",
  "dessert": "デザート",
  "detroit": "デトロイト",
  "deuce": "デュース",
  "deuterium": "デューテリウム",
  "devil": "デビル",
  "devon": "デヴォン",
  "devon rex": "デボンレックス",
  "dextrin": "デキストリン",
  "diagram": "ダイヤグラム",
  "diamond": "ダイヤモンド",
  "diana": "ダイアナ",
  "dictation": "ディクテーション",
  "digest": "ダイジェスト",
  "dilemma": "ジレンマ",
  "diode": "ダイオード",
  "directory": "ディレクトリ",
  "dirndl": "ダーンドル",
  "dirt": "ダート",
  "dirty": "ダーティ",
  "disc golf": "ディスクゴルフ",
  "disc jockey": "ディスクジョッキー",
  "diskette": "ディスケット",
  "disneyland": "ディズニーランド",
  "documentary": "ドキュメンタリー",
  "dodgeball": "ドッジボール",
  "dodo": "ドードー",
  "doll": "ドール",
  "domain": "ドメイン",
  "dome": "ドーム",
  "domestic violence": "ドメスティックバイオレンス",
  "donald duck": "ドナルドダック",
  "donut": "ドーナツ",
  "doo-wop": "ドゥーワップ",
  "door": "ドア",
  "dopamine": "ドーパミン",
  "doping": "ドーピング",
  "double": "ダブル",
  "double negative": "ダブルネガティブ",
  "double standard": "ダブルスタンダード",
  "dover": "ドーバー",
  "download": "ダウンロード",
  "downpicking": "ダウンピッキング",
  "dracula": "ドラキュラ",
  "dragon": "ドラゴン",
  "drain": "ドレイン",
  "dress": "ドレス",
  "dress code": "ドレスコード",
  "dressing": "ドレッシング",
  "dressmaker": "ドレスメーカー",
  "dressmaking": "ドレスメーキング",
  "drill": "ドリル",
  "driver": "ドライバー",
  "dry cleaning": "ドライクリーニング",
  "dryad": "ドライアド",
  "dubbing": "ダビング",
  "dubstep": "ダブステップ",
  "duckburg": "ダックバーグ",
  "duct": "ダクト",
  "dumbbell": "ダンベル",
  "dummy": "ダミー",
  "dundee": "ダンディー",
  "dutch wife": "ダッチワイフ",
  "dwarf": "ドワーフ",
  "dynamite": "ダイナマイト",
  "dyslexia": "ディスレクシア",
  "déjà vu": "デジャブ",
  "earphone": "イヤフォン",
  "earring": "イヤリング",
  "easel": "イーゼル",
  "ectoplasm": "エクトプラズム",
  "edgeworth–kuiper belt": "エッジワース・カイパーベルト",
  "edinburgh": "エディンバラ",
  "effector": "エフェクター",
  "eggnog": "エッグノッグ",
  "egyptian mau": "エジプシャンマウ",
  "eight": "エイト",
  "electra complex": "エレクトラコンプレックス",
  "electric bass": "エレクトリックベース",
  "electric guitar": "エレクトリック・ギター",
  "emerald": "エメラルド",
  "emperor penguin": "エンペラーペンギン",
  "emulator": "エミュレータ",
  "enchant": "エンチャント",
  "encore": "アンコール",
  "engine": "エンジン",
  "england": "イングランド",
  "english horn": "イングリッシュホルン",
  "epilogue": "エピローグ",
  "epinephrine": "エピネフリン",
  "episode": "エピソード",
  "epsilon": "エプシロン",
  "equalizer": "イコライザ",
  "error": "エラー",
  "escalator": "エスカレーター",
  "escape": "エスケープ",
  "esper": "エスパー",
  "estonia": "エストニア",
  "ethene": "エテン",
  "ethernet": "イーサネット",
  "ethos": "エトス",
  "ethylene": "エチレン",
  "ethyne": "エチン",
  "euphonium": "ユーフォニアム",
  "eurasia": "ユーラシア",
  "euro": "ユーロ",
  "eurobeat": "ユーロビート",
  "europium": "ユウロピウム",
  "eurovision": "ユーロビジョン",
  "euthanasia": "ユーサネイジア",
  "event": "イベント",
  "exbibit": "エクスビビット",
  "exbibyte": "エクスビバイト",
  "executive": "エグゼクティブ",
  "expert": "エキスパート",
  "eye contact": "アイコンタクト",
  "eyeshadow": "アイシャドー",
  "facsimile": "ファクシミリ",
  "factor": "ファクター",
  "failure": "フェイラー",
  "fall": "フォール",
  "fan club": "ファンクラブ",
  "fan fiction": "ファン・フィクション",
  "fanart": "ファンアート",
  "fanfic": "ファンフィック",
  "farad": "ファラド",
  "fascism": "ファシズム",
  "fascist": "ファシスト",
  "fashion": "ファッション",
  "fashion designer": "ファッションデザイナー",
  "fast food": "ファーストフード",
  "fastback": "ファストバック",
  "feedback": "フィードバック",
  "feet": "フィート",
  "fellatio": "フェラチオ",
  "felt": "フェルト",
  "felt pen": "フェルトペン",
  "feminism": "フェミニズム",
  "feminist": "フェミニスト",
  "fence": "フェンス",
  "fencing": "フェンシング",
  "fennec": "フェネック",
  "fergus": "ファーガス",
  "ferguson": "ファーガソン",
  "fermion": "フェルミオン",
  "fermium": "フェルミウム",
  "ferret": "フェレット",
  "ferry": "フェリー",
  "fiber optics": "ファイバーオプティックス",
  "fiction": "フィクション",
  "field hockey": "フィールドホッケー",
  "fighter": "ファイター",
  "figure": "フィギュア",
  "figure skate": "フィギュアスケート",
  "figure skating": "フィギュアスケーティング",
  "file": "ファイル",
  "finland": "フィンランド",
  "fire salamander": "ファイアサラマンダー",
  "firewall": "ファイアウォール",
  "firmware": "ファームウェア",
  "first": "ファースト",
  "first class": "ファーストクラス",
  "first lady": "ファーストレディ",
  "fish and chips": "フィッシュ・アンド・チップス",
  "five": "ファイブ",
  "flag": "フラッグ",
  "flamingo": "フラミンゴ",
  "flannel": "フランネル",
  "flash": "フラッシュ",
  "flea market": "フリーマーケット",
  "flint": "フリント",
  "flip": "フリップ",
  "floppy": "フロッピー",
  "floppy disk": "フロッピーディスク",
  "florence": "フローレンス",
  "florida": "フロリダ",
  "flow chart": "フローチャート",
  "fluorene": "フルオレン",
  "focus group": "フォーカスグループ",
  "folder": "フォルダ",
  "folk dance": "フォークダンス",
  "folk song": "フォークソング",
  "fondue": "フォンデュ",
  "foot": "フット",
  "football": "フットボール",
  "football helmet": "フットボールヘルメット",
  "fork": "フォーク",
  "forkball": "フォークボール",
  "forklift": "フォークリフト",
  "formant": "フォルマント",
  "fortune cookie": "フォーチュン・クッキー",
  "foundation": "ファンデーション",
  "four": "フォー",
  "four of a kind": "フォー・オブ・ア・カインド",
  "fourth": "フォース",
  "frame": "フレーム",
  "france": "フランス",
  "frankfort": "フランクフォート",
  "frappuccino": "フラペチーノ",
  "free software": "フリーソフトウェア",
  "free time": "フリータイム",
  "freelance": "フリーランス",
  "freelancer": "フリーランサー",
  "freeware": "フリーウェア",
  "freeze": "フリーズ",
  "fresnel lens": "フレネルレンズ",
  "fresno": "フレズノ",
  "fried chicken": "フライドチキン",
  "friendly": "フレンドリー",
  "frill": "フリル",
  "frisbee": "フリスビー",
  "fritter": "フリッター",
  "front office": "フロントオフィス",
  "fructose": "フルクトース",
  "fruit": "フルーツポンチ",
  "fruitcake": "フルーツケーキ",
  "fuchsia": "フューシャ",
  "fuck": "ファック",
  "fuckin’": "ファッキン",
  "full": "フル",
  "full house": "フルハウス",
  "full name": "フルネーム",
  "full screen": "フルスクリーン",
  "furazan": "フラザン",
  "fuse": "ヒューズ",
  "gaba": "ギャバ",
  "gabardine": "ギャバジン",
  "gaff": "ギャフ",
  "galactose": "ガラクトース",
  "gallery": "ギャラリー",
  "gallium": "ガリウム",
  "gambia": "ガンビア",
  "game": "ゲーム",
  "gamma": "ガンマ",
  "ganja": "ガンジャ",
  "garage": "ガレージ",
  "gargoyle": "ガーゴイル",
  "garnet": "ガーネット",
  "gate": "ゲート",
  "gazelle": "ガゼル",
  "gender": "ジェンダー",
  "general": "ゼネラル",
  "gentoo penguin": "ジェンツーペンギン",
  "george town": "ジョージタウン",
  "georgette": "ジョーゼット",
  "georgia": "ジョージア",
  "german shepherd dog": "ジャーマン・シェパード・ドッグ",
  "germany": "ジャーマニー",
  "gerrymander": "ゲリマンダー",
  "ghee": "ギー",
  "giant panda": "ジャイアントパンダ",
  "gibibit": "ギビビット",
  "gibibyte": "ギビバイト",
  "gibraltar": "ジブラルタル",
  "giga-": "ギガ",
  "gingerbread": "ジンジャーブレッド",
  "gingham": "ギンガム",
  "girdle": "ガードル",
  "girlfriend": "ガールフレンド",
  "glasgow": "グラスゴー",
  "globalization": "グローバリゼーション",
  "gloucester": "グロスター",
  "glucose": "グルコース",
  "gluon": "グルーオン",
  "glutamine": "グルタミン",
  "glyceride": "グリセリド",
  "glycerin": "グリセリン",
  "glycerol": "グリセロール",
  "glycoside": "グリコシド",
  "gnome": "ノーム",
  "goal": "ゴール",
  "goalkeeper": "ゴールキーパー",
  "goblin": "ゴブリン",
  "goggle": "ゴーグル",
  "golden gate bridge": "ゴールデン・ゲート・ブリッジ",
  "golden hamster": "ゴールデンハムスター",
  "golden lion tamarin": "ゴールデンライオンタマリン",
  "golf": "ゴルフ",
  "golf bag": "ゴルフバッグ",
  "golf club": "ゴルフクラブ",
  "gong": "ゴング",
  "good morning": "グッモーニン",
  "goods": "グッズ",
  "goofy": "グーフィー",
  "google": "グーグル",
  "gore": "ゴア",
  "gorilla": "ゴリラ",
  "gotcha": "ガッチャ",
  "gotham": "ゴッサム",
  "gown": "ガウン",
  "gradation": "グラデーション",
  "gramme": "グラム",
  "grand cayman": "グランドケイマン",
  "grand piano": "グランドピアノ",
  "granola": "グラノーラ",
  "graph": "グラフ",
  "graphic": "グラフィック",
  "graphic design": "グラフィックデザイン",
  "graphic designer": "グラフィックデザイナー",
  "graphics": "グラフィックス",
  "graphics card": "グラフィックスカード",
  "gravure": "グラビアアイドル",
  "gravy": "グレービー",
  "grayscale, greyscale": "グレースケール",
  "great barrier reef": "グレート・バリア・リーフ",
  "great britain": "グレートブリテン",
  "great plains": "グレートプレーンズ",
  "great pyrenees": "グレート・ピレニーズ",
  "great yarmouth": "グレート・ヤーマス",
  "greco-roman": "グレコローマン",
  "green peas": "グリーンピース",
  "green tuff": "グリーンタフ",
  "greenwich": "グリニッジ",
  "grenadines": "グレナディーン",
  "grey": "グレイ",
  "grey cup": "グレイ・カップ",
  "grizzly": "グリズリー",
  "group": "グループ",
  "guanidine": "グアニジン",
  "guard": "ガード",
  "guava": "グアバ",
  "guillotine": "ギロチン",
  "guinea": "ギニー",
  "guinea pig": "ギニーピッグ",
  "guinea-bissau": "ギニアビサウ",
  "guitar": "ギター",
  "guitarist": "ギタリスト",
  "gumption": "ガムプション",
  "gymnasium": "ジムナジウム",
  "gyroscope": "ジャイロスコープ",
  "haboob": "ハブーブ",
  "hacker": "ハッカー",
  "hair": "ヘア",
  "hair dryer": "ヘアドライヤー",
  "hairnet": "ヘアネット",
  "hairpin": "ヘアピン",
  "haiti": "ハイチ",
  "half": "ハーフ",
  "halloween": "ハロウィン",
  "halterneck": "ホルターネック",
  "hamburg steak": "ハンバーグステーキ",
  "hamburger": "ハンバーガー",
  "hammer": "ハンマー",
  "hampshire": "ハンプシャー",
  "hamster": "ハムスター",
  "hand model": "ハンドモデル",
  "handbag": "ハンドバッグ",
  "handball": "ハンドボール",
  "handkerchief": "ハンカチ",
  "hang glider": "ハンググライダー",
  "hanger": "ハンガー",
  "happy": "ハッピー",
  "happy ending": "ハッピーエンディング",
  "happy hardcore": "ハッピーハードコア",
  "hard disk": "ハードディスク",
  "hard disk drive": "ハードディスクドライブ",
  "hardcover": "ハードカバー",
  "hardware": "ハードウェア",
  "harlem": "ハーレム",
  "harmonica": "ハーモニカ",
  "harp": "ハープ",
  "harrisburg": "ハリスバーグ",
  "hartebeest": "ハーテビースト",
  "hartford": "ハートフォード",
  "hat trick": "ハットトリック",
  "hate speech": "ヘイトスピーチ",
  "hawaii": "ハワイ",
  "hazelnut": "ヘーゼルナッツ",
  "heading": "ヘディング",
  "headlight": "ヘッドライト",
  "headphone": "ヘッドフォン",
  "headset": "ヘッドセット",
  "health": "ヘルス",
  "heart": "ハート",
  "hedonism": "ヘドニズム",
  "helen": "ヘレン",
  "helena": "ヘレナ",
  "helicopter": "ヘリコプター",
  "helium": "ヘリウム",
  "helmet": "ヘルメット",
  "henry": "ヘンリー",
  "hero": "ヒーロー",
  "heroic": "ヒロイック",
  "heroine": "ヒロイン",
  "heroism": "ヒロイズム",
  "hessen": "ヘッセン",
  "high": "ハイカラ",
  "high card": "ハイカード",
  "high heel": "ハイヒール",
  "high-tech": "ハイテク",
  "hijack": "ハイジャック",
  "himalayan": "ヒマラヤン",
  "hint": "ヒント",
  "hit and run": "ヒットエンドラン",
  "hobart": "ホバート",
  "hockey": "ホッケー",
  "hogwarts": "ホグワーツ",
  "hollywood": "ハリウッド",
  "holmium": "ホルミウム",
  "holster": "ホルスター",
  "home": "ホーム",
  "home base": "ホームベース",
  "home directory": "ホームディレクトリ",
  "home page": "ホームページ",
  "home plate": "ホームプレート",
  "home run": "アベックホームラン",
  "homeostasis": "ホメオスタシス",
  "homer": "ホーマー",
  "homeroom": "ホームルーム",
  "homophobia": "ホモフォビア",
  "honey": "ハニー",
  "honeycomb": "ハニカム",
  "honeymoon": "ハネムーン",
  "honiara": "ホニアラ",
  "hood": "フード",
  "horoscope": "ホロスコープ",
  "horror": "ホラー",
  "horseradish": "ホースラディッシュ",
  "host": "ホスト",
  "hostess": "ホステス",
  "hot dog": "ホットドッグ",
  "hot pants": "ホットパンツ",
  "hot sauce": "ホットソース",
  "hotcake": "ホットケーキ",
  "hotchkiss": "ホッチキス",
  "hotel": "ホテル",
  "hotkey": "ホットキー",
  "hotplate": "ホットプレート",
  "house": "ハウス",
  "houston": "ヒューストン",
  "hovercraft": "ホバークラフト",
  "huddle": "ハドル",
  "hula hoop": "フラフープ",
  "humboldt penguin": "フンボルトペンギン",
  "hungary": "ハンガリー",
  "hunger strike": "ハンガー・ストライキ",
  "hunt": "ハント",
  "husband": "ハズバンド",
  "husky": "ハスキー",
  "hydra": "ハイドラ",
  "hydrazine": "ヒドラジン",
  "hydrazone": "ヒドラゾン",
  "hydroxylamine": "ヒドロキシルアミン",
  "hyena": "ハイエナ",
  "hyperinflation": "ハイパーインフレーション",
  "hyperlink": "ハイパーリンク",
  "hypertext": "ハイパーテキスト",
  "hyphen": "ハイフン",
  "ice bar": "アイスバー",
  "ice candy": "アイスキャンディー",
  "ice cream": "アイスクリーム",
  "ice hockey": "アイスホッケー",
  "iceland": "アイスランド",
  "icing": "アイシング",
  "icon": "アイコン",
  "idaho": "アイダホ",
  "identity": "アイデンティティ",
  "idol": "アイドル",
  "illinois": "イリノイ",
  "illumination": "イルミネーション",
  "imagination": "イマジネーション",
  "imidazole": "イミダゾール",
  "impound yard": "インパウンヤード",
  "indazole": "インダゾール",
  "indene": "インデン",
  "indiana": "インディアナ",
  "indianapolis": "インディアナポリス",
  "indole": "インドール",
  "inflation": "インフレーション",
  "info": "インフォ",
  "information": "インフォメーション",
  "inspiration": "インスピレーション",
  "install": "インストール",
  "installer": "インストーラー",
  "instant": "インスタント",
  "instant camera": "インスタントカメラ",
  "interior": "インテリア",
  "interior design": "インテリアデザイン",
  "interline": "インテル",
  "internet": "インターネット",
  "internet cafe": "インターネットカフェ",
  "interpol": "インターポール",
  "interview": "インタビュー",
  "interviewer": "インタビュアー",
  "inventory": "インベントリ",
  "inverter": "インバータ",
  "invoice": "インボイス",
  "iowa": "アイオワ",
  "iowa city": "アイオワシティ",
  "iqaluit": "イカルイト",
  "ireland": "アイルランド",
  "iron": "アイロン",
  "irony": "アイロニー",
  "isocyanide": "イソシアニド",
  "isonitrile": "イソニトリル",
  "italy": "イタリー",
  "item": "アイテム",
  "jack": "ジャック",
  "jackal": "ジャッカル",
  "jackson": "ジャクソン",
  "jaguar": "ジャガー",
  "jam session": "ジャムセッション",
  "jamaica": "ジャマイカ",
  "japan": "ジャパン",
  "japanese": "ジャパニーズ",
  "japanese bobtail": "ジャパニーズボブテイル",
  "jasmine": "ジャスミン",
  "jazz": "ジャズ",
  "jeans": "ジーンズ",
  "jeep": "ジープ",
  "jefferson": "ジェファーソン",
  "jefferson city": "ジェファーソンシティ",
  "jeffersontown": "ジェファーソンタウン",
  "jersey": "ジャージ",
  "jersey city": "ジャージーシティ",
  "jessica": "ジェシカ",
  "jigsaw puzzle": "ジグソーパズル",
  "jingle": "ジングル",
  "jitterbug": "ジルバ",
  "jockey": "ジョッキー",
  "jogging": "ジョギング",
  "joker": "ジョーカー",
  "joule": "ジュール",
  "joystick": "ジョイスティック",
  "juggling": "ジャグリング",
  "juice": "ジュース",
  "jukebox": "ジュークボックス",
  "jump": "ジャンプ",
  "juneau": "ジュノー",
  "jungle": "ジャングル",
  "kangaroo": "カンガルー",
  "kansas": "カンザス",
  "kappa": "カッパ",
  "kayak": "カヤック",
  "kazoo": "カズー",
  "kelvin": "ケルビン",
  "kennedy": "ケネディ",
  "kentucky": "ケンタッキー",
  "kerma": "カーマ",
  "kernel": "カーネル",
  "kerning": "カーニング",
  "ketchup": "ケチャップ",
  "keton": "ケトン",
  "keyboard": "キーボード",
  "keyframe": "キーフレーム",
  "keyman": "キーマン",
  "kibibit": "キビビット",
  "kibibyte": "キビバイト",
  "kick baseball": "キックベースボール",
  "kick scooter": "キックスケーター",
  "kickball": "キックボール",
  "kickoff": "キックオフ",
  "king": "キング",
  "king cobra": "キングコブラ",
  "king penguin": "キングペンギン",
  "kingston": "キングストン",
  "kingstown": "キングスタウン",
  "kinkajou": "キンカジュー",
  "kiosk": "キオスク",
  "kipper": "キッパー",
  "kiribati": "キリバス",
  "kiss": "キス",
  "kiwi fruit": "キウイフルーツ",
  "klaxon": "クラクション",
  "knee socks": "ニーソックス",
  "knife": "ナイフ",
  "knock": "ノック",
  "knot": "ノット",
  "knowledge": "ノレッジ",
  "kodiak": "コディアック",
  "korat": "コラット",
  "kuiper belt": "カイパーベルト",
  "laboratory": "ラボラトリー",
  "labrador": "ラブラドール",
  "labrador retriever": "ラブラドール・レトリバー",
  "lace": "レース",
  "lacrosse": "ラクロス",
  "lactose": "ラクトース",
  "lady": "レディ",
  "lagoon": "ラグーン",
  "lambda": "ラムダ",
  "lamp": "ランプ",
  "lancashire": "ランカシャー",
  "lansing": "ランシング",
  "lapel": "ラペル",
  "lapis lazuli": "ラピスラズリ",
  "laptop": "ラップトップ",
  "lard": "ラード",
  "laser": "レーザ",
  "lasik": "レーシック",
  "latency": "レイテンシ",
  "layer": "レイヤー",
  "layout": "レイアウト",
  "leader": "リーダー",
  "leadership": "リーダーシップ",
  "leafblower": "リーフブロワー",
  "lebanon": "レバノン",
  "left": "レフト",
  "leg warmer": "レッグウォーマー",
  "leicester": "レスター",
  "leisure": "レジャー",
  "leisurewear": "レジャーウエア",
  "lemming": "レミング",
  "lemon": "レモン",
  "lemon balm": "レモンバーム",
  "leotard": "レオタード",
  "lepton": "レプトン",
  "lesbian": "レズビアン",
  "lesser panda": "レッサーパンダ",
  "let's": "レッツ",
  "letter": "レター",
  "lettuce": "レタス",
  "library": "ライブラリー",
  "license or licence": "ライセンス",
  "life": "ライフ",
  "life cycle": "ライフサイクル",
  "lifework": "ライフワーク",
  "lift": "リフト",
  "liger": "ライガー",
  "light beer": "ライトビール",
  "light blue": "ライトブルー",
  "light table": "ライトテーブル",
  "lighter": "ライター",
  "lightsaber": "ライトセーバー",
  "lilac": "ライラック",
  "lima": "ライマ",
  "lima bean": "リマビーン",
  "limbo": "リンボー",
  "lime": "ライム",
  "limerick": "リムリック",
  "limonene": "リモネン",
  "limousine": "リムジン",
  "lincoln": "リンカーン",
  "line": "ライン",
  "liniment": "リニメント",
  "link": "リンク",
  "lion": "ライオン",
  "lion tamarin": "ライオンタマリン",
  "lip gloss": "リップグロス",
  "lip print": "リッププリント",
  "lipid": "リピド",
  "lipstick": "リップスティック",
  "lisp": "リスプ",
  "literacy": "リテラシー",
  "lithium": "リチウム",
  "little cayman": "リトルケイマン",
  "little rock": "リトルロック",
  "live": "ライブ",
  "live album": "ライブアルバム",
  "livermorium": "リバモリウム",
  "liverpool": "リヴァプール",
  "lizard": "リザード",
  "lizardman": "リザードマン",
  "loafer": "ローファー",
  "lobbying": "ロビイング",
  "lobbyist": "ロビイスト",
  "locker": "ロッカー",
  "lockout": "ロックアウト",
  "logic board": "ロジックボード",
  "lolita": "ロリ",
  "lollipop": "ロリポップ",
  "london": "ロンドン",
  "lonely": "ロンリー",
  "looks": "ルックス",
  "los angeles": "ロサンゼルス",
  "lossless": "ロスレス",
  "lotion": "ローション",
  "lotto": "ロト",
  "louisiana": "ルイジアナ",
  "lounge": "ラウンジ",
  "louver": "ルーバー",
  "love": "ラブ",
  "love letter": "ラブレター",
  "love song": "ラブソング",
  "lovebird": "ラブバード",
  "low blow": "ローブロー",
  "lowbrow": "ローブラウ",
  "lucifer": "ルシファー",
  "lucky": "ラッキー",
  "luke": "ルーク",
  "lumen": "ルーメン",
  "lunch": "ランチ",
  "luxemburg": "ラクセンバーグ",
  "luxon": "ルクソン",
  "lynch": "リンチ",
  "lynx": "リンクス",
  "lyric": "リリック",
  "macao": "マカオ",
  "macaroni": "マカロニ",
  "machine gun": "マシンガン",
  "madison": "マディソン",
  "madrid": "マドリッド",
  "maglite": "マグライト",
  "magma": "マグマ",
  "magus": "マグス",
  "maid": "メイド",
  "mail": "メール",
  "main": "メイン",
  "main page": "メインページ",
  "mainboard": "メインボード",
  "maine coon": "メインクーン",
  "maintenance": "メンテナンス",
  "majuro": "マジュロ",
  "makeup": "メイクアップ",
  "malaria": "マラリア",
  "malay": "マレー",
  "malaysia": "マレーシア",
  "male rape": "メイル・レイプ",
  "mallet": "マレット",
  "maltese": "マルチーズ",
  "malware": "マルウェア",
  "mammoth": "マンモス",
  "mana": "マナ",
  "manager": "マネージャー",
  "manatee": "マナティー",
  "manchester": "マンチェスター",
  "mandrill": "マンドリル",
  "mango": "マンゴー",
  "mangosteen": "マンゴスチン",
  "manhole": "マンホール",
  "manicure": "マニキュア",
  "manitoba": "マニトバ",
  "mannequin": "マネキン",
  "mansion": "マンション",
  "manticore": "マンティコア",
  "manx": "マンクス",
  "maple syrup": "メープルシロップ",
  "marathon": "マラソン",
  "margarine": "マーガリン",
  "margay": "マーゲイ",
  "marimba": "マリンバ",
  "marker": "マーカー",
  "marker pen": "マーカーペン",
  "marking pen": "マーキングペン",
  "marmalade": "マーマレード",
  "marmot": "マーモット",
  "mars": "マーズ",
  "marshmallow": "マシュマロ",
  "martial arts": "マーシャルアーツ",
  "mary jane": "メリージェーン",
  "maryland": "メリーランド",
  "marzipan": "マジパン",
  "mascara": "マスカラ",
  "mascot": "マスコット",
  "mask": "マスク",
  "masking tape": "マスキングテープ",
  "masochism": "マゾヒズム",
  "massachusetts": "マサチューセッツ",
  "master": "マスター",
  "master plan": "マスタープラン",
  "masturbation": "マスターベーション",
  "mauritius": "モーリシャス",
  "mcdonald": "マクドナルド",
  "measure": "メジャー",
  "meatball": "ミートボール",
  "mebibit": "メビビット",
  "mebibyte": "メビバイト",
  "mechanic": "メカニック",
  "meerkat": "ミーアキャット",
  "megaphone": "メガホン",
  "melancholy": "メランコリー",
  "melbourne": "メルボルン",
  "meme": "ミーム",
  "memory": "メモリー",
  "mental health": "メンタルヘルス",
  "mercury": "マーキュリー",
  "merfolk": "マーフォーク",
  "merge": "マージ",
  "mermaid": "マーメイド",
  "merry christmas": "メリークリスマス",
  "merry-go-round": "メリーゴーラウンド",
  "messiah": "メシア",
  "meter": "メーター",
  "methane": "メタン",
  "mexico": "メキシコ",
  "mexico city": "メキシコシティ",
  "michigan": "ミシガン",
  "mickey mouse": "ミッキーマウス",
  "microgramme": "マイクログラム",
  "microphone": "マイクロフォン",
  "midriff": "ミッドリフ",
  "mill": "ミル",
  "millennium": "ミレニアム",
  "milligramme": "ミリグラム",
  "milwaukee": "ミルウォーキー",
  "mime": "マイム",
  "mind map": "マインドマップ",
  "mini": "ミニ",
  "minimalism": "ミニマリズム",
  "miniskirt": "ミニスカート",
  "mink": "ミンク",
  "minneapolis": "ミネアポリス",
  "minnesota": "ミネソタ",
  "minnie mouse": "ミニーマウス",
  "mint": "ミント",
  "minutiae": "マニューシャ",
  "miracle": "ミラクル",
  "mississippi": "ミシシッピ",
  "missouri": "ミズーリ",
  "mistress": "ミストレス",
  "mobile": "モバイル",
  "mocap": "モーキャプ",
  "modem": "モデム",
  "modern": "モダン",
  "modernism": "モダニズム",
  "module": "モジュール",
  "money": "マネー",
  "money laundering": "マネー・ロンダリング",
  "monitoring": "モニタリング",
  "monkey": "モンキー",
  "monkey wrench": "モンキーレンチ",
  "monochrome": "モノクローム",
  "monocle": "モノクル",
  "monopoly": "モノポリー",
  "monsoon": "モンスーン",
  "monster": "モンスター",
  "montana": "モンタナ",
  "montgomery": "モンゴメリー",
  "montpelier": "モントピリア",
  "montreal": "モントリオール",
  "montserrat": "モントセラト",
  "moon": "ムーン",
  "moonroof": "ムーンルーフ",
  "moped": "モペッド",
  "morpholine": "モルホリン",
  "moscovium": "モスコビウム",
  "moscow": "モスコー",
  "mosque": "モスク",
  "motel": "モーテル",
  "motherboard": "マザーボード",
  "motion capture": "モーションキャプチャ",
  "motocross": "モトクロス",
  "motorboat": "モーターボート",
  "motorcar": "モーターカー",
  "mouse": "マウス",
  "muffin": "マフィン",
  "muffler": "マフラー",
  "mule": "ミュール",
  "mulligan": "マリガン",
  "muon": "ミューオン",
  "muse": "ミューズ",
  "mushroom": "マッシュルーム",
  "music video": "ミュージックビデオ",
  "musician": "ミュージシャン",
  "mustang": "マスタング",
  "mustard": "マスタード",
  "mute": "ミュート",
  "myanmar": "ミャンマー",
  "nail polish": "ネイルポリッシュ",
  "naive": "ナイーブ",
  "name": "ネーム",
  "nanosecond": "ナノセカンド",
  "nanotech": "ナノテク",
  "nanotechnology": "ナノテクノロジー",
  "naphtha": "ナフサ",
  "naphthalene": "ナフタレン",
  "naphthyridine": "ナフチリジン",
  "napkin": "ナプキン",
  "naples": "ネイプルズ",
  "narcissism": "ナルシシズム",
  "narcissist": "ナルシシスト",
  "narcist": "ナルシスト",
  "nasa": "ナサ",
  "nashville": "ナッシュビル",
  "national football league": "ナショナルフットボールリーグ",
  "nationalism": "ナショナリズム",
  "navigate": "ナビゲート",
  "nazism": "ナチズム",
  "nebraska": "ネブラスカ",
  "necklace": "ネックレス",
  "nekton": "ネクトン",
  "neoteny": "ネオテニー",
  "nessie": "ネッシー",
  "netizen": "ネチズン",
  "network": "ネットワーク",
  "neural network": "ニューラルネットワーク",
  "neuron": "ニューロン",
  "neutrino": "ニュートリノ",
  "nevada": "ネバダ",
  "nevis": "ネイビス",
  "new britain": "ニューブリテン",
  "new brunswick": "ニューブランズウィック",
  "new caledonia": "ニューカレドニア",
  "new england": "ニューイングランド",
  "new guinea": "ニューギニア",
  "new hampshire": "ニューハンプシャー",
  "new jersey": "ニュージャージー",
  "new mexico": "ニューメキシコ",
  "new orleans": "ニューオーリンズ",
  "new south wales": "ニューサウスウェールズ",
  "new york": "ニューヨーク",
  "new zealand": "ニュージーランド",
  "newcomer": "ニューカマー",
  "newfie": "ニューフィー",
  "newfoundland": "ニューファンドランド",
  "news": "ニュース",
  "news desk": "ニュースデスク",
  "newscaster": "ニュースキャスター",
  "newsflash": "ニュースフラッシュ",
  "newsletter": "ニュースレター",
  "newsroom": "ニュースルーム",
  "newton": "ニュートン",
  "nha trang": "ニャチャン",
  "nice": "ナイス",
  "nice guy": "ナイスガイ",
  "nickname": "ニックネーム",
  "niger": "ナイジャ",
  "nigeria": "ナイジェリア",
  "nigger": "ニガー",
  "night": "ナイト",
  "night table": "ナイトテーブル",
  "nightclub": "ナイトクラブ",
  "nightingale": "ナイチンゲール",
  "nightstand": "ナイトスタンド",
  "nihonium": "ニホニウム",
  "nike": "ナイキ",
  "nile": "ナイル",
  "nine": "ナイン",
  "nipper": "ニッパー",
  "nitrile": "ニトリル",
  "no pair": "ノーペア",
  "no-show": "ノーショー",
  "noise": "ノイズ",
  "nonsense": "ナンセンス",
  "normal": "ノーマル",
  "north augusta": "ノースオーガスタ",
  "north carolina": "ノースカロライナ",
  "north charleston": "ノースチャールストン",
  "north dakota": "ノースダコタ",
  "north kingstown": "ノースキングスタウン",
  "northampton": "ノーサンプトン",
  "northern territory": "ノーザンテリトリー",
  "norway": "ノルウェー",
  "norwegian forest cat": "ノルウェージャンフォレストキャット",
  "norwich": "ノリッチ",
  "nostalgia": "ノスタルジア",
  "note": "ノート",
  "notebook": "ノートブック",
  "nova scotia": "ノバスコシア",
  "number one": "ナンバーワン",
  "nylon": "ナイロン",
  "nymph": "ニンフ",
  "oatmeal": "オートミール",
  "obama": "オバマ",
  "obamacare": "オバマケア",
  "obelisk": "オベリスク",
  "oboe": "オーボー",
  "occult": "オカルト",
  "ocean": "オーシャン",
  "oceania": "オセアニア",
  "ocelot": "オセロット",
  "ocicat": "オシキャット",
  "octadecane": "オクタデカン",
  "odin": "オーディン",
  "office": "オフィスレディ",
  "office pool": "オフィスプール",
  "oganesson": "オガネソン",
  "ogre": "オーガ",
  "ohio": "オハイオ",
  "oklahoma": "オクラホマ",
  "oklahoma city": "オクラホマシティ",
  "olefin": "オレフィン",
  "olive oil": "オリーブオイル",
  "olympia": "オリンピア",
  "olympic": "オリンピック",
  "omega": "オメガ",
  "omicron": "オミクロン",
  "on air": "オンエアー",
  "one pair": "ワンペア",
  "one-piece": "ワンピース",
  "onium": "オニウム",
  "ontario": "オンタリオ",
  "open source": "オープンソース",
  "operating system": "オペレーティングシステム",
  "opossum": "オポッサム",
  "oral history": "オーラル・ヒストリー",
  "orangutan": "オランウータン",
  "orchestra": "オーケストラ",
  "organdy": "オーガンジー",
  "orgasm": "オーガズム",
  "orlando": "オーランド",
  "orleans": "オーリンズ",
  "osazone": "オサゾン",
  "oscar": "オスカー",
  "oslo": "オスロ",
  "ottawa": "オタワ",
  "ottoman": "オットマン",
  "over": "オーバー",
  "overall": "オーバーオール",
  "overblouse": "オーバーブラウス",
  "overdose": "オーバードース",
  "overtime": "オーバータイム",
  "ovum": "オヴム",
  "own goal": "オウンゴール",
  "owner": "オーナー",
  "oxazole": "オキサゾール",
  "oxime": "オキシム",
  "oxytocin": "オキシトシン",
  "ozone hole": "オゾンホール",
  "page": "ページ",
  "pair": "ペア",
  "paisley": "ペーズリー",
  "palmtop": "パームトップ",
  "palmtop computer": "パームトップコンピューター",
  "pancake": "パンケーキ",
  "panda": "パンダ",
  "panpipe": "パンパイプ",
  "pansy": "パンジー",
  "pantomime": "パントマイム",
  "pants": "パンツ",
  "panty": "パンティー",
  "papaya": "パパイア",
  "paper": "ペーパー",
  "paperback": "ペーパーバック",
  "papua": "パプア",
  "papua new guinea": "パプアニューギニア",
  "parabola": "パラボラ",
  "parallel": "パラレル",
  "parallel world": "パラレルワールド",
  "paralympic": "パラリンピック",
  "paris": "パリス",
  "parity": "パリティー",
  "parka": "パーカー",
  "parking meter": "パーキングメーター",
  "parody": "パロディ",
  "parsec": "パーセク",
  "parser": "パーサー",
  "part-time": "パートタイム",
  "particle": "パーティクル",
  "partition": "パーティション",
  "partnership": "パートナーシップ",
  "party": "パーティー",
  "pass": "パス",
  "passing": "パッシング",
  "passion fruit": "パッションフルーツ",
  "passport": "パスポート",
  "password": "パスワード",
  "pastel": "パステル",
  "patrick": "パトリック",
  "patrol": "パトロール",
  "patrol car": "パトロールカー",
  "pawn": "ポーン",
  "peace": "ピース",
  "peace sign": "ピースサイン",
  "peach": "ピーチ",
  "peanut": "ピーナッツ",
  "peanut butter": "ピーナッツバター",
  "pearl": "パール",
  "pearl harbor": "パールハーバー",
  "pebibit": "ペビビット",
  "pebibyte": "ペビバイト",
  "peccary": "ペッカリー",
  "pedicure": "ペディキュア",
  "pedometer": "ペドメーター",
  "pegasus": "ペガサス",
  "pekinese": "ペキニーズ",
  "pelican": "ペリカン",
  "pen name": "ペンネーム",
  "pence": "ペンス",
  "penguin": "ペンギン",
  "pennsylvania": "ペンシルベニア",
  "penny": "ペニー",
  "pentagon": "ペンタゴン",
  "pentathlon": "ペンタスロン",
  "penthouse": "ペントハウス",
  "peppermint": "ペパーミント",
  "pepperoni": "ペパロニ",
  "peptide": "ペプチド",
  "peridot": "ペリドット",
  "permanent": "パーマネント",
  "persia": "ペルシア",
  "personal computer": "パーソナルコンピューター",
  "perspective": "パースペクティブ",
  "peru": "ペルー",
  "pest": "ペスト",
  "petticoat": "ペチコート",
  "pharaoh": "ファラオ",
  "phenanthrene": "フェナントレン",
  "phenanthridine": "フェナントリジン",
  "phenazine": "フェナジン",
  "phenol": "フェノール",
  "pheromone": "フェロモン",
  "philadelphia": "フィラデルフィア",
  "phoenix": "フェニックス",
  "phonon": "フォノン",
  "phosphine": "ホスフィン",
  "photograph": "フォトグラフ",
  "phthalazine": "フタラジン",
  "phthalein": "フタレイン",
  "pianist": "ピアニスト",
  "piano": "ピアノ",
  "pica": "パイカ",
  "piccolo": "ピッコロ",
  "picene": "ピセン",
  "pick": "ピック",
  "pidgin": "ピジン",
  "piedmont": "ピードモント",
  "pierre": "ピア",
  "pilates": "ピラティス",
  "pinch": "ピンチ",
  "pinch runner": "ピンチランナー",
  "pineapple": "パイナップル",
  "pinene": "ピネン",
  "ping pong": "ピンポン",
  "pink": "ピンク",
  "pint": "パイント",
  "pipe": "パイプ",
  "piperazine": "ピペラジン",
  "piperidine": "ピペリジン",
  "pistachio": "ピスタチオ",
  "pistol": "ピストル",
  "piston": "ピストン",
  "pitch": "ピッチ",
  "pitcher": "ピッチャー",
  "pixel": "ピクセル",
  "placebo": "プラシーボ",
  "plane": "プレーン",
  "planetarium": "プラネタリウム",
  "plankton": "プランクトン",
  "plasma": "プラズマ",
  "plastic model": "プラスチックモデル",
  "plate tectonics": "プレートテクトニクス",
  "platform": "プラットホーム",
  "platonism": "プラトニズム",
  "play": "プレー",
  "playlist": "プレイリスト",
  "plier": "プライヤ",
  "plough": "プラウ",
  "plug-in": "プラグイン",
  "pocket": "ポケット",
  "podcast": "ポッドキャスト",
  "poker": "ポーカー",
  "poland": "ポーランド",
  "pole dance": "ポールダンス",
  "polio": "ポリオ",
  "polish": "ポリッシュ",
  "polo": "ポロ",
  "polo shirt": "ポロシャツ",
  "polyester": "ポリエステル",
  "polygraph": "ポリグラフ",
  "polynosic": "ポリノジック",
  "polyurethane": "ポリウレタン",
  "pomona": "ポモナ",
  "pompon": "ポンポン",
  "pony": "ポニー",
  "ponytail": "ポニーテール",
  "poodle": "プードル",
  "pop culture": "ポップカルチャー",
  "pop-up": "ポップアップ",
  "porch": "ポーチ",
  "pornography": "ポルノグラフィ",
  "porphin": "ポルフィン",
  "porphyrin": "ポルフィリン",
  "porridge": "ポリッジ",
  "port augusta": "ポートオーガスタ",
  "port lincoln": "ポートリンカーン",
  "port louis": "ポートルイス",
  "port of spain": "ポートオブスペイン",
  "port-au-prince": "ポルトープランス",
  "portfolio": "ポートフォリオ",
  "portion": "ポーション",
  "portrait": "ポートレート",
  "poster": "ポスター",
  "postmodern": "ポストモダン",
  "postmodernism": "ポストモダニズム",
  "postproduction": "ポストプロダクション",
  "potato": "ポテト",
  "power": "パワー",
  "powerful": "パワフル",
  "prairie dog": "プレーリードッグ",
  "prescore": "プレスコ",
  "presentation": "プレゼンテーション",
  "press conference": "プレスカンファレンス",
  "pressure": "プレッシャー",
  "pretty": "プリティー",
  "pretzel": "プレッツェル",
  "prince": "プリンス",
  "prince edward island": "プリンスエドワードアイランド",
  "princess": "プリンセス",
  "print": "プリント",
  "printer": "プリンター",
  "privacy": "プライバシー",
  "privacy policy": "プライバシーポリシー",
  "processor": "プロセッサ",
  "program": "プログラム",
  "projector": "プロジェクタ",
  "proletaria": "プロレタリア",
  "pronghorn": "プロングホーン",
  "property": "プロパティ",
  "propose": "プロポーズ",
  "propylene": "プロピレン",
  "protease": "プロテアーゼ",
  "protein": "プロテイン",
  "protestant": "プロテスタント",
  "protestantism": "プロテスタンティズム",
  "providence": "プロビデンス",
  "prune": "プルーン",
  "prussia": "プロシア",
  "psychic": "サイキック",
  "psychometry": "サイコメトリー",
  "pteridine": "プテリジン",
  "pterin": "プテリン",
  "public": "パブリック",
  "public domain": "パブリックドメイン",
  "public relations": "パブリック・リレーションズ",
  "pudding": "プディング",
  "pulp fiction": "パルプ・フィクション",
  "pulsar": "パルサー",
  "puma": "プーマ",
  "pumpkin": "パンプキン",
  "pumps": "パンプス",
  "punch": "パンチ",
  "punkish": "パンキッシュ",
  "punt": "パント",
  "pure": "ピュア",
  "purine": "プリン",
  "puritan": "ピューリタン",
  "purse": "パース",
  "putty": "パテ",
  "puzzle": "パズル",
  "pygmy": "ピグミー",
  "pygmy chimpanzee": "ピグミーチンパンジー",
  "pylon": "パイロン",
  "pyramid": "ピラミッド",
  "pyran": "ピラン",
  "pyrazine": "ピラジン",
  "pyrazole": "ピラゾール",
  "pyridazine": "ピリダジン",
  "pyridine": "ピリジン",
  "pyrimidine": "ピリミジン",
  "pyrrole": "ピロール",
  "qatar": "カタール",
  "quaker": "クエーカー",
  "quality": "クォリティ",
  "quark": "クォーク",
  "quarter": "クォーター",
  "quarterback": "クォーターバック",
  "quarterly": "クオータリー",
  "quasar": "クエーサー",
  "quebec city": "ケベック・シティー",
  "queen": "クイーン",
  "queens": "クイーンズ",
  "queensland": "クイーンズランド",
  "query": "クエリ",
  "question mark": "クエスチョンマーク",
  "quidditch": "クィディッチ",
  "quilt": "キルト",
  "quinazoline": "キナゾリン",
  "quinoline": "キノリン",
  "quinone": "キノン",
  "quinoxaline": "キノキサリン",
  "quiz": "クイズ",
  "racetrack": "レーストラック",
  "racket": "ラケット",
  "radar": "レーダー",
  "radiator": "ラジエーター",
  "radio": "ラジオ",
  "radio control": "ラジオコントロール",
  "ragdoll": "ラグドール",
  "railgun": "レールガン",
  "raincoat": "レインコート",
  "raisin": "レーズン",
  "raleigh": "ローリー",
  "rampway": "ランプウェー",
  "ranch dressing": "ランチドレッシング",
  "random access memory": "ランダムアクセスメモリ",
  "range": "レンジ",
  "ranger": "レンジャー",
  "rape": "レイプ",
  "rare": "レア",
  "raspberry": "ラズベリー",
  "ray tracing": "レイトレーシング",
  "rayon": "レーヨン",
  "reaction": "リアクション",
  "read-only memory": "リードオンリーメモリ",
  "reading": "レディング",
  "real money trade": "リアルマネートレード",
  "reality show": "リアリティショー",
  "rebrand": "リブランド",
  "receipt": "レシート",
  "recipe": "レシピ",
  "record": "レコード",
  "record player": "レコードプレーヤー",
  "recorder": "レコーダー",
  "recording studio": "レコーディングスタジオ",
  "recreation": "レクリエーション",
  "recruit": "リクルート",
  "reebok": "リーボック",
  "reel": "リール",
  "referendum": "レファレンダム",
  "reggae": "レゲエ",
  "rehabilitation": "リハビリテーション",
  "reject": "リジェクト",
  "relax": "リラックス",
  "remember": "リメンバー",
  "remix": "リミックス",
  "remote control": "リモートコントロール",
  "renewal": "リニューアル",
  "repeat": "リピート",
  "repertory": "レパートリー",
  "replica": "レプリカ",
  "repository": "リポジトリ",
  "request": "リクエスト",
  "resource": "リソース",
  "response": "レス",
  "restaurant": "レストラン",
  "revenge match": "リベンジマッチ",
  "reverse engineering": "リバースエンジニアリング",
  "review": "レビュー",
  "revolver": "リボルバー",
  "reykjavik": "レイキャヴィーク",
  "rhapsody": "ラプソディ",
  "rhinestone": "ラインストーン",
  "rhode island": "ロードアイランド",
  "rhythm and blues": "リズム・アンド・ブルース",
  "richmond": "リッチモンド",
  "rider": "ライダー",
  "right": "ライト",
  "ring": "リング",
  "rival": "ライバル",
  "rivet": "リブビット",
  "road roller": "ロードローラー",
  "robot": "ロボット",
  "rock climbing": "ロッククライミング",
  "rocket": "ロケット",
  "rocking chair": "ロッキングチェア",
  "roger": "ラジャー",
  "role-playing game": "ロールプレイングゲーム",
  "roller hockey": "ローラーホッケー",
  "rollercoaster": "ローラーコースター",
  "romanji": "ロマンジ",
  "romantic": "ロマンチック",
  "roommate": "ルームメイト",
  "rose quartz": "ローズクォーツ",
  "rough": "ラフ",
  "router": "ルーター",
  "royal flush": "ロイヤルフラッシュ",
  "ruble": "ルーブル",
  "ruby": "ルビー",
  "ruffle": "ラッフル",
  "rugby": "ラグビー",
  "rumania": "ルーマニア",
  "russian blue": "ロシアンブルー",
  "russian roulette": "ロシアンルーレット",
  "sabotage": "サボタージュ",
  "saccharin": "サッカリン",
  "sack": "サック",
  "sacrament": "サクラメント",
  "sadism": "サディズム",
  "sadist": "サディスト",
  "sadistic": "サディスティック",
  "safari": "サファリ",
  "safe": "セーフ",
  "saint john": "セントジョン",
  "saint kitts": "セントキッツ",
  "saint paul": "セントポール",
  "saint vincent": "セントビンセント",
  "salad": "サラダ",
  "salad dressing": "サラダドレッシング",
  "salamander": "サラマンダー",
  "salem": "セイラム",
  "sales": "セールス",
  "salesman": "セールスマン",
  "salisbury": "ソールズベリー",
  "salmon": "サーモン",
  "salsa": "サルサ",
  "salt lake city": "ソルトレイクシティ",
  "sambar": "サンバー",
  "san jose": "サンノゼ",
  "sand": "サンド",
  "sandal": "サンダル",
  "sandbag": "サンドバッグ",
  "sandpaper": "サンドペーパー",
  "sandwich": "サンドイッチ",
  "sandwichman": "サンドイッチマン",
  "sanskrit": "サンスクリット",
  "santa": "サンタ",
  "santa claus": "サンタクロース",
  "sapphire": "サファイア",
  "sapphism": "サフィズム",
  "saran wrap": "サランラップ",
  "saskatchewan": "サスカチュワン",
  "saturn": "サターン",
  "saucer": "ソーサー",
  "sausage": "ソーセージ",
  "saxophone": "サクソフォン",
  "scalar": "スカラー",
  "scale": "スケール",
  "scandal": "スキャンダル",
  "scanty": "スキャンティー",
  "scarab": "スカラブ",
  "scenario": "シナリオ",
  "scheme": "スキーム",
  "schnauzer": "シュナウザー",
  "school": "スクール",
  "school bus": "スクールバス",
  "science": "サイエンス",
  "science fiction": "サイエンス・フィクション",
  "scientology": "サイエントロジー",
  "scion": "サイオン",
  "scoop": "スクープ",
  "scooter": "スクーター",
  "scoreboard": "スコアボード",
  "scotland": "スコットランド",
  "scotland yard": "スコットランドヤード",
  "scottish fold": "スコティッシュフォールド",
  "scout": "スカウト",
  "scout report": "スカウトレポート",
  "scrap": "スクラップ",
  "scrapbook": "スクラップブック",
  "scratch ticket": "スクラッチチケット",
  "screen test": "スクリーンテスト",
  "screenshot": "スクリーンショット",
  "screwdriver": "スクリュードライバー",
  "script": "スクリプト",
  "scuba diving": "スキューバ・ダイビング",
  "sea bass": "シーバス",
  "seafood": "シーフード",
  "seal": "シール",
  "sealand": "シーランド",
  "seat": "シート",
  "seat belt": "シートベルト",
  "seattle": "シアトル",
  "secant": "セカント",
  "second": "セカンド",
  "second album": "セカンドアルバム",
  "seesaw": "シーソー",
  "self-service": "セルフサービス",
  "selfie": "セルフィー",
  "semicolon": "セミコロン",
  "seminar": "セミナー",
  "sensor": "センサ",
  "sentence": "センテンス",
  "serenade": "セレナード",
  "serif": "セリフ",
  "serval": "サーバル",
  "service": "サービス",
  "service games": "セガ",
  "set list": "セットリスト",
  "seven": "セブン",
  "sewing set": "ソーイングセット",
  "sex appeal": "セックスアピール",
  "sexual harassment": "セクシャルハラスメント",
  "sexy": "セクシー",
  "seychelles": "セイシェル",
  "shadow": "シャドー",
  "shakespeare": "シェイクスピア",
  "shar pei": "シャー・ペイ",
  "shareware": "シェアウェア",
  "sharp": "シャープ",
  "sharpener": "シャープナー",
  "shawl": "ショール",
  "shell": "シェル",
  "shelter": "シェルター",
  "sherry": "シェリー",
  "shift": "シフト",
  "shih tzu": "シーズー",
  "ship": "シップ",
  "shirt": "シャツ",
  "shoes": "シューズ",
  "shop": "ショップ",
  "short": "ショート",
  "short pants": "ショートパンツ",
  "shortcut": "ショートカット",
  "shortcut key": "ショートカットキー",
  "shorts": "ショーツ",
  "shortstop": "ショートストップ",
  "shotgun": "ショットガン",
  "shovel": "ショベル",
  "show window": "ショーウィンドウ",
  "showcase": "ショーケース",
  "shred": "シュレッド",
  "shredder": "シュレッダー",
  "shuffle": "シャッフル",
  "shutdown": "シャットダウン",
  "siberian": "サイベリアン",
  "siberian husky": "シベリアン・ハスキー",
  "sice": "サイス",
  "sigma": "シグマ",
  "sign-off": "サインオフ",
  "silage": "サイレージ",
  "silicon valley": "シリコンバレー",
  "silk hat": "シルクハット",
  "silk road": "シルクロード",
  "silo": "サイロ",
  "simulation": "シミュレーション",
  "simulation game": "シミュレーションゲーム",
  "sindbad": "シンドバッド",
  "sine": "サイン",
  "singapura": "シンガプーラ",
  "single": "シングル",
  "sioux city": "スーシティ",
  "siphon": "サイフォン",
  "siren": "サイレン",
  "sister": "シスター",
  "situation": "シチュエーション",
  "sketchbook": "スケッチブック",
  "ski lift": "スキーリフト",
  "skid mark": "スキッドマーク",
  "skier": "スキーヤー",
  "skiing": "スキーイング",
  "skin": "スキン",
  "skinhead": "スキンヘッド",
  "skirt": "スカート",
  "skort": "スコート",
  "skunk": "スカンク",
  "skydiving": "スカイダイビング",
  "slacks": "スラックス",
  "slash": "スラッシュ",
  "sleeping bag": "スリーピングバッグ",
  "sleeve": "スリーブ",
  "slide": "スライド",
  "slider": "スライダー",
  "slime": "スライム",
  "slip": "スリップ",
  "slipper": "スリッパ",
  "slot machine": "スロットマシン",
  "slovakia": "スロバキア",
  "slow loris": "スローロリス",
  "slow motion": "スローモーション",
  "slum": "スラム",
  "slump": "スランプ",
  "slur": "スラー",
  "smart": "スマート",
  "smartphone": "スマートフォン",
  "smile": "スマイル",
  "snack": "スナック",
  "snack bar": "スナックバー",
  "sneaker": "スニーカー",
  "snood": "スヌード",
  "snow plow": "スノープラウ",
  "snowboard": "スノーボード",
  "snowmobile": "スノーモービル",
  "soca": "ソカ",
  "soccer": "サッカー",
  "social media": "ソーシャルメディア",
  "sofa": "ソファ",
  "soft": "ソフト",
  "soft drink": "ソフトドリンク",
  "softball": "ソフトボール",
  "softcover": "ソフトカバー",
  "software": "ソフトウェア",
  "soliton": "ソリトン",
  "solomon": "ソロモン",
  "somali": "ソマリ",
  "somalia": "ソマリア",
  "somaliland": "ソマリランド",
  "sonar": "ソナー",
  "song": "ソング",
  "sonnet": "ソネット",
  "sorcery": "ソーサリー",
  "soul": "ソウル",
  "sound card": "サウンドカード",
  "sound effect": "サウンドエフェクト",
  "soundtrack": "サウンドトラック",
  "soup": "スープ",
  "source code": "ソースコード",
  "south carolina": "サウスカロライナ",
  "south charleston": "サウスチャールストン",
  "south dakota": "サウスダコタ",
  "south kingstown": "サウスキングスタウン",
  "southampton": "サウサンプトン",
  "spade": "スペード",
  "spaghetti": "スパゲティー",
  "spain": "スペイン",
  "spandex": "スパンデックス",
  "spangle": "スパンコール",
  "spanking": "スパンキング",
  "special": "スペシャル",
  "speech": "スピーチ",
  "speed": "スピード",
  "speed bump": "スピードバンプ",
  "speed gun": "スピードガン",
  "spell": "スペル",
  "spelling": "スペリング",
  "sphinx": "スフィンクス",
  "spokesman": "スポークスマン",
  "sponsor": "スポンサー",
  "sponsorship": "スポンサーシップ",
  "spoon": "スプーン",
  "sports bar": "スポーツバー",
  "sports bra": "スポーツブラ",
  "sports drink": "スポーツドリンク",
  "spotlight": "スポットライト",
  "spring": "スプリング",
  "springfield": "スプリングフィールド",
  "sprinkler": "スプリンクラー",
  "sprint": "スプリント",
  "spyware": "スパイウェア",
  "squall": "スコール",
  "sri lanka": "スリランカ",
  "st. john's": "セントジョンズ",
  "stadium": "スタジアム",
  "staff": "スタッフ",
  "stained glass": "ステンドグラス",
  "stainless": "ステンレス",
  "stainless steel": "ステンレス・スティール",
  "stalker": "ストーカー",
  "stand": "スタンド",
  "stanley cup": "スタンレーカップ",
  "stapler": "ステープラー",
  "star": "スター",
  "star wars": "スター・ウォーズ",
  "static": "スタティック",
  "station": "ステーション",
  "steak": "ステーキ",
  "stearin": "ステアリン",
  "steering wheel": "ステアリング・ホイール",
  "stenographer": "ステムグラファー",
  "steroid": "ステロイド",
  "stew": "シチュー",
  "steward": "スチュワード",
  "stewardess": "スチュワーデス",
  "stick": "ステッキ",
  "stocking": "ストッキング",
  "stonehenge": "ストーンヘンジ",
  "stop": "ストップ",
  "stopwatch": "ストップウオッチ",
  "storage": "ストレージ",
  "straight": "ストレート",
  "straight flush": "ストレートフラッシュ",
  "streaking": "ストリーキング",
  "street": "ストリート",
  "stress": "ストレス",
  "stretch": "ストレッチ",
  "stretcher": "ストレッチャー",
  "stretching": "ストレッチング",
  "stripper": "ストリッパー",
  "studio": "スタジオ",
  "study": "スタディー",
  "stun gun": "スタンガン",
  "stunt": "スタント",
  "stuntman": "スタントマン",
  "sturm und drang": "シュトゥルム・ウント・ドラング",
  "style": "スタイル",
  "stylesheet": "スタイルシート",
  "subculture": "サブカルチャー",
  "sudden death": "サドンデス",
  "sufism": "スーフィズム",
  "suit": "スート",
  "sulfone": "スルホン",
  "sulfoxide": "スルホキシド",
  "summer": "サマー",
  "sunday": "サンデー",
  "sundress": "サンドレス",
  "sunglass": "サングラス",
  "super bowl": "スーパーボール",
  "super, super-": "スーパー",
  "superhero": "スーパーヒーロー",
  "superman": "スーパーマン",
  "supermodel": "スーパーモデル",
  "suplex": "スープレックス",
  "supplement": "サプリメント",
  "surfboard": "サーフボード",
  "surfer": "サーファー",
  "surfing": "サーフィン",
  "suspense": "サスペンス",
  "swan": "スワン",
  "swansea": "スウォンジー",
  "swaziland": "スワジランド",
  "sweater": "セーター",
  "sweatshirt": "スウェットシャツ",
  "sweatsuit": "スウェットスーツ",
  "sweden": "スウェーデン",
  "sweet corn": "スイートコーン",
  "swimming": "スイミング",
  "sydney": "シドニー",
  "sylph": "シルフ",
  "symphony": "シンフォニー",
  "symposium": "シンポジウム",
  "synapse": "シナプス",
  "synthesizer": "シンセサイザー",
  "syracuse": "シラキュース",
  "sysop": "シスオペ",
  "system operator": "システムオペレーター",
  "table mountain": "テーブルマウンテン",
  "tablespoon": "テーブルスプーン",
  "tablet": "タブレット",
  "tabloid": "タブロイド",
  "tachyon": "タキオン",
  "taffeta": "タフタ",
  "talkie": "トーキー",
  "tallahassee": "タラハシー",
  "tamarin": "タマリン",
  "tambourine": "タンバリン",
  "tangent": "タンジェント",
  "tank top": "タンクトップ",
  "tankini": "タンキニ",
  "tapping": "タッピング",
  "tardyon": "ターディオン",
  "tasmania": "タスマニア",
  "tea bag": "ティーバッグ",
  "teacup": "ティーカップ",
  "team play": "チームプレー",
  "teaspoon": "ティースプーン",
  "tebibit": "テビビット",
  "tebibyte": "テビバイト",
  "technical": "テクニカル",
  "telepathy": "テレパシー",
  "telephone": "テレホン",
  "telephone card": "テレホンカード",
  "teleport": "テレポート",
  "teleportation": "テレポーテーション",
  "telestrator": "テレストレーター",
  "teletype": "テレタイプ",
  "temp": "テンプ",
  "template": "テンプレート",
  "tennessee": "テネシー",
  "tennessine": "テネシン",
  "tennis": "テニス",
  "tennis court": "テニスコート",
  "tenor": "テナー",
  "tension": "テンション",
  "terminal": "ターミナル",
  "terpene": "テルペン",
  "terrier": "テリア",
  "terrorism": "テロリズム",
  "terrorist": "テロリスト",
  "tesla": "テスラ",
  "tesla coil": "テスラコイル",
  "texas": "テキサス",
  "texas city": "テキサスシティ",
  "text": "テキスト",
  "textbook": "テキストブック",
  "thank you": "サンキュー",
  "thermostat": "サーモスタット",
  "theta": "シータ",
  "thiazine": "チアジン",
  "thiazole": "チアゾール",
  "thiophene": "チオフェン",
  "third": "サード",
  "thoroughbred": "サラブレッド",
  "thread": "スレッド",
  "three": "スリー",
  "three of a kind": "スリー・オブ・ア・カインド",
  "three rs": "スリーアールズ",
  "three-piece": "スリーピース",
  "thrill ride": "スリルライド",
  "thriller": "スリラー",
  "thumbnail": "サムネイル",
  "tiara": "ティアラ",
  "tibet": "チベット",
  "ticket": "ティケット",
  "tigon": "タイゴン",
  "time machine": "タイムマシン",
  "time travel": "タイムトラベル",
  "time traveller": "タイムトラベラー",
  "timeline": "タイムライン",
  "timesheet": "タイムシート",
  "timpani": "ティンパニ",
  "tire": "タイヤ",
  "tissue": "ティッシュ",
  "title": "タイトル",
  "toast": "トースト",
  "toaster": "トースター",
  "toilet": "トイレット",
  "toilet paper": "トイレットペーパー",
  "token": "トークン",
  "tomato": "トマト",
  "tomato juice": "トマトジュース",
  "tomography": "トモグラフィー",
  "tong": "トング",
  "tooltip": "ツールチップ",
  "top hat": "トップハット",
  "topeka": "トピカ",
  "topic": "トピック",
  "topless": "トップレス",
  "topping": "トッピング",
  "torbay": "トーベイ",
  "toreador pants": "トレアドールパンツ",
  "tornado": "トルネード",
  "toronto": "トロント",
  "totem": "トーテム",
  "totem pole": "トーテムポール",
  "tottenham": "トッテナム",
  "touch panel": "タッチパネル",
  "touchdown": "タッチダウン",
  "touchpad": "タッチパッド",
  "toughness": "タフネス",
  "tour": "ツアー",
  "trackback": "トラックバック",
  "trackpad": "トラックパッド",
  "tractor": "トラクター",
  "trading card game": "トレーディングカードゲーム",
  "traffic": "トラフィック",
  "trailer": "トレーラー",
  "trainer": "トレーナー",
  "tram": "トラム",
  "trampoline": "トランポリン",
  "trance": "トランス",
  "transgender": "トランスジェンダー",
  "transistor": "トランジスタ",
  "transistor radio": "トランジスタラジオ",
  "transmitter": "トランスミッター",
  "transmodern": "トランスモダン",
  "transsexual": "トランスセクシャル",
  "trauma": "トラウマ",
  "tray": "トレー",
  "treadmill": "トレッドミル",
  "treble": "トレブル",
  "tree": "ツリー",
  "trench coat": "トレンチコート",
  "trend": "トレンド",
  "trenton": "トレントン",
  "triathlon": "トライアスロン",
  "trick": "トリック",
  "trigger": "トリガー",
  "tritium": "トリチウム",
  "trombone": "トロンボーン",
  "trophy": "トロフィー",
  "tropylium": "トロピリウム",
  "trouble": "トラブル",
  "troublemaker": "トラブルメーカー",
  "troubleshooter": "トラブルシューター",
  "troubleshooting": "トラブルシューティング",
  "troy": "トロイ",
  "truck": "トラック",
  "trump": "トランプ",
  "trump game": "トランプゲーム",
  "trunks": "トランクス",
  "trust": "トラスト",
  "tuba": "チューバ",
  "tube top": "チューブトップ",
  "tucson": "ツーソン",
  "tulip": "チューリップ",
  "tungsten": "タングステン",
  "tunic": "チュニック",
  "tunnel": "トンネル",
  "turkey": "ターキー",
  "turkish angora": "ターキッシュアンゴラ",
  "turkish van": "ターキッシュバン",
  "turn": "ターン",
  "tutorial": "チュートリアル",
  "tuxedo": "タキシード",
  "twintail": "ツインテール",
  "two pair": "ツーペア",
  "typeface": "タイプフェイス",
  "typewriter": "タイプライター",
  "typing": "タイピング",
  "typography": "タイポグラフィ",
  "ultra": "ウルトラ",
  "underscore": "アンダースコア",
  "unicode": "ユニコード",
  "unicorn": "ユニコーン",
  "uniform": "ユニフォーム",
  "uninstall": "アンインストール",
  "unit": "ユニット",
  "united nations": "ユナイテッドネーションズ",
  "ununhexium": "ウンウンヘキシウム",
  "upload": "アップロード",
  "upright piano": "アップライトピアノ",
  "upsilon": "ユプシロン",
  "uptempo": "アップテンポ",
  "user interface": "ユーザインタフェース",
  "utah": "ユタ",
  "utopia": "ユートピア",
  "vanadium": "バナジウム",
  "vancouver": "バンクーバー",
  "vanitas": "ヴァニタス",
  "vault": "ヴォールト",
  "vegetable": "ベジタブル",
  "vegetarian": "ベジタリアン",
  "vehicle": "ビークル",
  "venice": "ベニス",
  "vermont": "バーモント",
  "versus": "バーサス",
  "vibrator": "バイブレーター",
  "victoria": "ヴィクトリア",
  "video card": "ビデオカード",
  "video game": "ビデオゲーム",
  "videotape": "ビデオテープ",
  "vienna": "ヴィエンナ",
  "vietnam": "ベトナム",
  "viking": "ヴァイキング",
  "vinyl record": "ビニールレコード",
  "violin": "バイオリン",
  "viral": "バイラル",
  "virginia": "バージニア",
  "virtual reality": "バーチャルリアリティ",
  "virus": "バイラス",
  "vitamin": "ビタミン",
  "vitriol": "ビトリオール",
  "vocoder": "ボコーダー",
  "voice": "ボイス",
  "voicemail": "ボイスメール",
  "volleyball": "バレーボール",
  "waffle": "ワッフル",
  "waiter": "ウェイター",
  "waitress": "ウェイトレス",
  "wales": "ウェールズ",
  "wallaby": "ワラビー",
  "wallaroo": "ワラルー",
  "wallflower": "ウォールフラワー",
  "waltz": "ワルツ",
  "warwick": "ウォリック",
  "washington": "ワシントン",
  "watch": "ウオッチ",
  "water": "ワーラー",
  "watt": "ワット",
  "wear": "ウエア",
  "web browser": "ウェブブラウザ",
  "web design": "ウェブデザイン",
  "website": "ウェブサイト",
  "weekly": "ウィークリー",
  "welsh corgi": "ウェルシュ・コーギー",
  "west virginia": "ウェストバージニア",
  "whale watching": "ホエールウォッチング",
  "whisky": "ウイスキー",
  "white": "ホワイト",
  "white gold": "ホワイトゴールド",
  "white hole": "ホワイトホール",
  "white house": "ホワイトハウス",
  "white shirt": "ホワイトシャツ",
  "widescreen": "ワイドスクリーン",
  "wife": "ワイフ",
  "wikipedia": "ウィキペディア",
  "wiktionary": "ウィクショナリー",
  "wildebeest": "ウィルドビースト",
  "win-win": "ウィンウィン",
  "winch": "ウインチ",
  "window": "ウインドー",
  "window washer": "ウィンドウウォッシャー",
  "wine": "ワイン",
  "winglet": "ウィングレット",
  "wink": "ウインク",
  "winter": "ウィンター",
  "wire stripper": "ワイヤーストリッパー",
  "wizard": "ウィザード",
  "wolf": "ウルフ",
  "wombat": "ウォンバット",
  "wonder woman": "ワンダーウーマン",
  "wonderful": "ワンダフル",
  "woodchuck": "ウッドチャック",
  "worcester": "ウスター",
  "word processor": "ワードプロセッサ",
  "workshop": "ワークショップ",
  "workspace": "ワークスペース",
  "world cup": "ワールドカップ",
  "world music": "ワールドミュージック",
  "world series": "ワールドシリーズ",
  "worm": "ワーム",
  "wormhole": "ワームホール",
  "wrapping": "ラッピング",
  "wrench": "レンチ",
  "wrestler": "レスラー",
  "wrestling": "レスリング",
  "writer": "ルポライター",
  "wyvern": "ワイバーン",
  "xanthene": "キサンテン",
  "yacht": "ヨット",
  "yellow": "イエロー",
  "yellowknife": "イエローナイフ",
  "yo-yo": "ヨーヨー",
  "yobibit": "ヨビビット",
  "yobibyte": "ヨビバイト",
  "yogi": "ヨギ",
  "york": "ヨーク",
  "yorkshire": "ヨークシャー",
  "yorkshire terrier": "ヨークシャー・テリア",
  "youtuber": "ユーチューバー",
  "zebibit": "ゼビビット",
  "zebibyte": "ゼビバイト",
  "zebu": "ゼブ",
  "zeta": "ゼータ",
  "zip code": "ジップコード",
  "zombie": "ゾンビ",
  "β-carotene": "ベータカロテン"
};

walk(document.body);

function walk(node) 
{
	// I stole this function from here:
	// http://is.gd/mwZp7E
	
	var child, next;
	
	var tagName = node.tagName ? node.tagName.toLowerCase() : "";
	if (tagName == 'input' || tagName == 'textarea') {
		return;
	}
	if (node.classList && node.classList.contains('ace_editor')) {
		return;
	}

	switch ( node.nodeType )  
	{
		case 1:  // Element
		case 9:  // Document
		case 11: // Document fragment
			child = node.firstChild;
			while ( child ) 
			{
				next = child.nextSibling;
				walk(child);
				child = next;
			}
			break;

		case 3: // Text node
			handleText(node);
			break;
	}
}

function handleReplace(match, g1, g2, g3, g4) {
	return g1 + jpMap[g2.toLowerCase()] + (g3 || "") + g4;
}

function handleText(textNode) 
{
	var v = textNode.nodeValue;

	v = v.replace(jpRegex, handleReplace);
	
	textNode.nodeValue = v;
}


